#:schema node_modules/wrangler/config-schema.json
name = "haiku42"
compatibility_date = "2024-10-01"
pages_build_output_dir = ".output/public"

# Specify the Node.js version
[build]
command = "npm run build"

[build.environment]
NODE_VERSION = "22.4.1"

# Routes configuration
[[routes]]
pattern = "haiku42.net"
custom_domain = true

# Production environment configuration
[env.production]
name = "production"

# Enable caching for the haiku-image API route
[[env.production.routes]]
pattern = "https://haiku42.net/api/haiku-image*"
[env.production.routes.cache]
cache_everything = true
edge_ttl = 86400
browser_ttl = 86400

# Enable caching for the haiku API route (GET requests)
[[env.production.routes]]
pattern = "https://haiku42.net/api/haiku?id=*"
[env.production.routes.cache]
cache_everything = true
edge_ttl = 86400
browser_ttl = 86400

# Disable caching for POST requests to the haiku API route
[[env.production.routes]]
pattern = "https://haiku42.net/api/haiku"
method = "POST"
[env.production.routes.cache]
cache_everything = false

# Variable bindings (uncomment and modify as needed)
# [vars]
# MY_VARIABLE = "production_value"

# Secrets (uncomment and add your secrets in the Cloudflare dashboard)
# [secrets]
# MY_SECRET = "my-secret-value"
