// ── CLIMATE-ECHO (10%) ──────────────────────────────────────────
// Landscapes showing environmental change. Tightly scoped to
// outdoor/ecological settings.

export const climateEcho = {
    name: "climate-echo",
    weight: 10,
    // climate-echo leans into moment-change and absence compositions;
    // minimal/pivot are too thin for this mode's emotional register.
    compositionWeights: { turned: 35, "absence-led": 25, juxtaposed: 20, layered: 15, anchored: 5, pivot: 0, minimal: 0 },
    scenes: [
      // Cluster 1: smoke-heat-drought — wildfire scars, heat haze, drought, urban heat island
      {
        frames: [
          "wildfire scar, one year later",
          "school soccer field under wildfire haze",
          "rooftop in the urban heat island, tar paper blistering",
          "carbon capture unit on the warehouse wall, fans running",
          "smoke season, air quality monitor on the school fence",
          "dried lake bed, salt crust cracking",
          "forest floor after the beetle kill",
          "ski trail with patches of bare ground",
          "high school track under smoke haze, lane lines barely visible",
          "ski lift maze on brown ground, season postponed",
          "county fairground cooling tent, asphalt still radiating at dusk",
          "substation yard in heat haze, warning flags snapping",
          "rooftop solar panels in the haze",
        ],
        anchors: [
          "smoke haze turning the sun orange",
          "drought cracks in the garden bed",
          "pine beetle dust falling from the bark",
          "wildflowers in December",
          "air quality sign on the school fence, red today",
          "smoke column visible from the ridge, three counties over",
          "street trees dead from three summers of heat, still standing",
          "smoke dimming the solar array by noon",
          "cedar sapling browned on the south side only",
          "cedar bark peeled by heat on the south-facing slope",
          "storm siren test while the sky stays clear and yellow",
          "wind turbine shadow sweeping through the wheat",
          "sprinkler head misting cracked soil",
          "schoolyard maple dropping leaves in late August",
          "orchard netting pulled over fruit already sun-scorched",
        ],
        sensory: [
          "air so dry the lips crack",
          "haze smell, not quite smoke",
          "grit in the wind from the dry lakebed",
          "smoke season particulates gritty on the teeth",
          "heat dome: air shimmering above the suburb at 9am",
          "ash smell weeks after fire season ends",
          "noon light orange through the smoke, shadows missing",
          "the smell of dry pine in a forest that should not be dry",
          "heat rising from the road at midnight in July",
          "ash dust on the tongue",
          "burnt eucalyptus in the morning marine layer",
          "the heat held in the playground rubber after sunset",
          "copper taste after wildfire rain",
          "char smoke trapped under morning inversion in the valley",
          "dust settling on the porch before the wind arrives",
        ],
        traces: [
          "new trees planted where the old ones burned",
          "wildfire defensible space cleared around the house, bare dirt ring",
          "prescribed burn permit laminated to the fence post",
          "prescribed fire smoke visible from the highway, orange cones out",
          "cooling center sign zip-tied to the fence",
          "cooling center flyers under windshield wipers",
          "cooling center map taped inside the library window",
          "window AC units stacked behind the hardware store by June",
          "shade cloth stretched over the school blacktop fence",
          "heat advisory poster taped over last month's flood notice",
          "fire-smart landscaping sign staked in gravel instead of lawn",
        ],
        absences: [
          "the ridgeline bare to the summit, no white band",
          "the glacier the trail was named for",
          "dead oak standing, shadow too thin to sit in",
          "the ski lodge shuttered since the drought years",
          "the shade tree the yard had last summer",
          "dry creek bed, smooth stones bleaching in the sun",
          "the snowplow stakes stacked untouched by the shed",
          "the sled hill grass already green in mid-January",
          "the snowmelt ditch dry before school lets out",
          "the snow fence stored away all winter",
          "the creek crossing plank, high and dry in January",
        ],
        turns: [
          "the first rain after weeks of smoke",
          "the smoke column bending with the wind shift",
          "the sea fog burning off to reveal the blackened hillside",
          "the weather station alarm going off in the empty field",
        ],
      },

      // Cluster 2: coastal-tidal — sea level rise, king tide, salt marsh, oyster beds, dock
      {
        frames: [
          "shoreline, ten feet closer than the photo",
          "marsh at high tide, the dock barely clearing",
          "river mouth at king tide, parking lot cones out",
          "dock pilings in king tide water, parking meter posts half submerged",
          "salt marsh at dawn, tide still high",
          "boat ramp where the tide chart stops matching",
          "tide gauge bolted to the pier",
        ],
        anchors: [
          "tide mark on the seawall, higher than the last one",
          "microplastics glittering in the tide wrack",
          "horseshoe crab upside down above the tide line",
          "fish gasping at the warm surface",
          "seabirds following the trawler inland",
        ],
        sensory: [
          "salt crust on everything near the shore",
          "brackish water smell in the ditch",
          "mud smell from the marsh at king tide",
          "salt wind carrying marsh mud through the parking lot",
          "warm seawater stink around the low-tide rocks in spring",
          "salt marsh at low tide, more mud than usual",
        ],
        traces: [
          "high-water mark on the bridge piling",
          "seawall raised another foot",
          "evacuation route arrow painted on the seawall",
          "tide table folded in the ferry kiosk window",
          "salt-stained zip-tie around the storm shutter",
        ],
        absences: [
          "the beach that was wider in the photos",
          "the oyster beds, empty shells only",
          "the summer the river didn't reach the sea",
          "dock ladder with no water under it",
          "the fishing shack, half in the water now",
          "the marsh boardwalk section removed after repeated king tides",
          "the eelgrass line on the chart, not in the water",
        ],
        turns: [
          "the tide nudging the last dry board on the dock",
          "a wave crossing the seawall onto the parking lot",
          "the king tide gauge tipping past the red mark",
        ],
      },

      // Cluster 3: inland-flood — atmospheric river, levee, retention pond, sandbag, suburban flood
      {
        frames: [
          "levee path, the concrete patched again",
          "atmospheric river aftermath, road still running with water",
          "flood-adapted ground floor, everything raised two feet",
          "community garden after the flood",
          "suburban retention pond in August, ringed with cracked mud",
          "county road with a fresh washout",
          "riverbank where the PFAS foam has gathered at the bend",
        ],
        anchors: [
          "rain gauge overflowing, third time this month",
          "white foam drifting in a slow arc at the river bend",
          "gutter still overflowing two days after the atmospheric river",
          "algae bloom on the lake, bright green",
          "snow geese circling, nowhere to land",
          "storm drain burping brown water after ten dry weeks",
        ],
        sensory: [
          "the particular stillness before a storm that doesn't come",
          "warm rain, the parking lot steaming in January",
          "ozone sharp before the atmospheric river hits",
          "mud smell where the snow went too fast",
          "sweet chemical smell of the PFAS foam at the water's edge",
        ],
        traces: [
          "depth marker painted on the doorframe of the flood-adapted house",
          "mylar emergency blanket left on the evacuation trail",
          "sandbag wall left by the garage",
          "flood line painted inside the shed",
          "flood vent cut into the old brick foundation",
          "flood gauge sticker on the school gym door",
          "sandbags drying in the driveway",
          "flood gauge painted on the pump house",
          "rain barrel overflow hose routed to a new trench",
          "raised floor joists in the ground-floor apartment",
        ],
        absences: [
          "the neighborhood that moved uphill, old foundations still visible",
          "the wetland behind the new levee, drained",
          "the basement steps where the waterline mark stopped",
          "the storm drain grate, dry through the wet season",
        ],
        turns: [
          "a crack running through the reservoir mud",
          "the levee seep finding the low spot in the gravel",
          "the rain gauge overflowing again with no one watching",
        ],
      },

      // Cluster 3: agriculture-seasonal-drift — orchards, vineyards, migration, salmon, irrigation, pollinators
      {
        frames: [
          "orchard in bloom three weeks ahead of schedule",
          "backyard plum tree, too-early spring",
          "vineyard with heat-tolerant stakes, old trellis wire still up",
          "migration station, binoculars and a clipboard",
          "cornfield edge, irrigation gun ticking at dawn",
          "orchard row under hail netting",
          "orchard with sunburned fruit",
          "salmon ladder, water barely covering the lower rung",
          "farm pond aerator running through an unseasonal warm night",
          "the old swimming hole, not deep enough anymore",
          "riverbed with the waterline dropping",
        ],
        anchors: [
          "blossoms opening before the bees arrive",
          "a monarch on the December lawn",
          "robin pulling a worm from January ground",
          "creek running warm in November",
          "an unfamiliar brown bird at the feeder, unrecorded",
          "bird bander noting a species not recorded here before",
          "salmon nosing at warm shallows and turning back",
          "windbreak net snapping in the gust",
          "cicadas starting before the sun is down",
          "pumpkins setting in July heat, vines still thirsty",
          "milkweed leaves curled at the edges",
          "a single apple, sunburned on the branch",
          "ice cubes of hail in the gutter",
          "two plovers on a roped-off patch of sand",
          "ice edges lacing the cattails, thin",
        ],
        sensory: [
          "heat rising from the blacktop in February",
          "pollen coating the car two months early",
          "wet wool smell of rain in what should still be drought",
          "creek water warm enough to wade in October",
          "green pond smell after three hot days",
          "warm wind off the reservoir, not a spring wind",
          "plastic greenhouse heat rolling out at sunrise",
          "thunder rolling past without rain",
          "well water tasting faintly of iron this summer",
          "air conditioner condensate dripping into dust by noon",
        ],
        traces: [
          "almanac predictions crossed out, revised",
          "seed vault label, variety: heat-tolerant",
          "bird count notebook, fewer entries each year",
          "invasive species removal bags stacked at the trailhead",
          "drought-resistant garden sign beside the xeriscaped front yard",
          "cool roof grant sticker on the rowhouse downspout",
        ],
        absences: [
          "the field where cotton grew before the water table dropped",
          "the empty suet cage in late April",
          "the orchard, pulled out after the third crop failure",
          "the snowpack that fed the reservoir, gone by March",
          "the spring the river ran clear, before the algae",
          "the ice on the pond that never formed",
          "the frogs calling after rain",
          "the frost date in the farmer's notebook, crossed out again",
          "the fall migration count board with two species crossed off",
          "vacant nesting platform on the pylon",
          "irrigation ditch without a trickle",
          "the bait shop minnow tank line, dry above the hose",
          "fishing quota board with last year's numbers crossed out",
        ],
        turns: [
          "the irrigation gun shutting off mid-arc",
          "a flock turning mid-air, doubling back",
          "the hail netting snapping taut on one side",
          "the salmon turning at the warm shallows",
        ],
      },

      // Cluster 4: marine-coastal-restoration — kelp, seagrass, mangroves, coral, coastal adaptation
      {
        frames: [
          "kelp forest restoration site, offshore buoys marking the grid",
          "mangrove planting, knee-deep in mud",
          "seagrass meadow, hip-deep, researchers hand-planting",
          "coral reef, half bleached",
          "coastal restoration site, volunteer boats anchored offshore",
          "intertidal zone survey, researchers at low tide",
        ],
        anchors: [
          "seagrass sprig tied to a survey stake, just planted",
          "kelp tangled in the marina piping, July",
          "snow crab traps stacked on the dock, season closed early",
          "blue crab trap pulled with mostly jellyfish inside",
          "sandbar that wasn't there last summer",
          "the mangrove prop root catching the falling tide",
          "mangrove propagule tied to a survey stake in the shallows",
        ],
        sensory: [
          "the chemical sweetness of the algae bloom at the shoreline",
          "mud cracking under the marsh grass roots",
          "salt wind sharp off the restoration site",
          "warm seawater smell, the reef too shallow now",
          "kelp iodine on the tide line",
        ],
        traces: [
          "before-and-after satellite photos on the bulletin board",
          "kelp cultivation buoy line visible from the shore path",
          "dive shop chalkboard listing inshore routes only",
          "survey flag line marking the seagrass transplant grid",
        ],
        absences: [
          "the kelp canopy visible in old dive footage, not in the water now",
          "the oyster reef marked on the old chart, silted in",
          "the coral color in the photograph on the dive shop wall",
        ],
        turns: [
          "a gust rattling the flood-gauge ribbon",
          "the tide uncovering the seagrass roots, still holding",
          "the kelp stipe brushing the research diver's mask",
        ],
      },

      // Cluster 6: cryosphere-thaw — glaciers, permafrost, peat bog, ice shelf, boreal monitoring
      {
        frames: [
          "permafrost road buckled into waves",
          "peat bog restoration, sphagnum moss in labeled plastic trays",
          "weather station on the alpine ridge, anemometer spinning",
          "glacier terminus, gravel where ice was",
          "boreal pond at thaw, bubbles rising in lines",
          "snow gauge in the alpine basin, less stick showing each season",
        ],
        anchors: [
          "ice shelf calving into green water",
          "tree rings, the thin ones at the outside",
          "permafrost hummock pushing up through the gravel road",
          "moose tracks crossing where the ice should still hold",
          "lichen brown on the rock that used to face away from the sun",
        ],
        sensory: [
          "methane smell low over the thawing bog",
          "thin ice that shouldn't be thin yet",
          "frost on the inside of the cabin window, thinner than last year",
          "wet peat smell rising under the rubber boot",
          "the silence after the bog thumps once",
        ],
        traces: [
          "peat core in a labeled tube on the field station table",
          "glacier extent marker, the old one twenty meters behind you now",
          "research transect tape strung between two stunted spruce",
          "monitoring well cap on the cracked permafrost",
        ],
        absences: [
          "the glacier the trail was named for, only gravel now",
          "the snow line on the photograph from twenty years ago",
          "the lichen mat gone from the rock face since the warm winters",
        ],
        turns: [
          "a piece of the glacier face dropping into the water",
          "the thaw pond surface ringing once with no wind",
          "the ice cornice giving way along the ridge",
        ],
      },

      // Cluster 7: inland-restoration-energy — floating solar, wind turbines, prairie, rewilding, agrivoltaics
      {
        frames: [
          "floating solar farm on the reservoir",
          "wind turbines in the wheat, shadow sweeping the rows",
          "restored prairie, seedlings flagged white",
          "rewilding site, former cornfield, year three",
          "agrivoltaic field, soybeans in panel shadow",
          "carbon-capture pilot at the highway pull-off, fans humming",
        ],
        anchors: [
          "floating pontoon garden on the reservoir surface",
          "solar panel on the barn roof, one bird on the frame",
          "rewilding cattle moving through the fenced former wheat field",
          "monarch on the prairie restoration flag",
          "wind turbine blade laid on the trailer flat, paint chipped",
        ],
        sensory: [
          "heat at night that won't let up",
          "low thrum of wind turbines two fields over",
          "wet ash smell in the rain barrel",
          "the metallic taste of the tap water this month",
        ],
        traces: [
          "rewilding boundary sign, new species list laminated to the post",
          "soil carbon sampling tubes capped on the field truck bed",
          "clipboard at the prairie plot, native species checked off",
        ],
        absences: [
          "the public splash pad schedule board, season shortened again",
          "the mosquito cloud at dusk, gone after the spray truck",
          "the cornfield section the rewilding ate back, no stalks left",
        ],
        turns: [
          "the air quality sign flipping from yellow to red",
          "the solar panel fan kicking on in the silence",
          "the rewilding cattle stopping at the old fence line",
        ],
      },
    ],
};
