// ── COMIC-GLIMPSE (5%) ──────────────────────────────────────────
// Gentle absurdity in mundane settings. All entries share
// retail/errand/daily-life spaces.

export const comicGlimpse = {
    name: "comic-glimpse",
    weight: 5,
    frames: [
      "grocery store self-checkout",
      "drive-through, engine idling",
      "gym at 6am, only three people",
      "elevator, two strangers and a dog",
      "dentist's waiting room",
      "car wash, inside, going through",
      "parent-teacher conference hallway",
      "DMV, number B-247",
      "dog park, the small dog section",
      "IKEA showroom, a couple not speaking",
      "hardware store, wrong aisle again",
      "yoga class, first day, back row",
      "zoom meeting, mic still on",
      "parking lot, forgot which level",
      "buffet line, considering the shrimp",
      "airplane middle seat",
      "the line for the bathroom at the concert",
      "oil change waiting room, daytime TV",
      "self-storage hallway, unit 4B",
      "the returns counter, receipt crumpled",
      "curbside pickup spot, number seven, hazards on",
      "the apartment package locker, code not working",
      "furniture assembly floor, pieces everywhere",
      "coffee shop, waiting for the name to be called wrong",
      "the pharmacy drive-through, third window",
      "food court, deciding which line is shorter",
      "robot delivery bot stopped on the curb, blinking",
      "airport security bin retrieval scramble",
      "the smart home speaker corner of the kitchen",
      "outdoor dining, app to see the menu",
      "car dealership waiting area, free popcorn",
      "the post office self-service kiosk",
      "hotel check-in, app says room is ready",
      "the treadmill desk in the open-plan office",
      "rideshare pickup corner, three drivers circling",
      "mall food court after school",
      "laundromat at 9pm, one dryer left",
      "roadside motel ice machine",
      "office kitchen, one spoon left",
      "supermarket freezer aisle, door fogged over",
      "supermarket floral section, one helium balloon escaped",
      "pet store checkout, squeaky toy trial aisle",
      "video call waiting room, camera accidentally front-facing",
      "office break room, cake in the fridge, no note",
      "warehouse club checkout, receipt to the floor",
      "bus stop under a broken schedule board",
      "library copier room with a paper jam",
      "movie theater lobby after credits",
      "grocery delivery pickup shelf, bags alphabetized, one upside down",
      "office hot-desk zone, everyone guarding one outlet",
      "airport rideshare lot, everyone holding up the same phone screen",
      "big-box garden aisle in January, inflatable flamingos on clearance",
      "apartment mailroom with five identical unclaimed umbrella stands",
    ],
    anchors: [
      "someone talking to the self-checkout machine",
      "toddler waving at everyone, nobody waving back, then everyone waving back",
      "dog walking its owner across the street",
      "man reading shampoo bottles like literature",
      "pigeon walking into the coffee shop when the door opens",
      "child explaining gravity to a younger child, mostly wrong",
      "someone asleep upright on the train, perfectly balanced",
      "the automatic door opening for nobody",
      "squirrel outsmarting the bird feeder, again",
      "someone carrying a single balloon through the rain",
      "the roomba bumping the same corner for the third time",
      "a crow dropping a walnut in the crosswalk for cars to crack",
      "someone walking into a pull door, then a push door",
      "the sprinkler hitting the mail carrier every day at the same time",
      "kid on the swings, shoes flying off at the peak",
      "cat ignoring the expensive toy, sitting in the box",
      "someone sneezing alone and saying bless you to themselves",
      "the fitted sheet winning, again",
      "two strangers reaching for the same avocado",
      "the phone autocorrecting something perfectly correct into nonsense",
      "smart speaker lighting up from the other room",
      "delivery driver photographing the package on the wrong doorstep",
      "someone filming their food from four angles before eating",
      "someone setting up a ring light beside the fries",
      "Bluetooth pairing to the wrong speaker in the whole coffee shop",
      "man arguing with the GPS after it was right",
      "a toddler accidentally starting a video call to a grandparent",
      "the robot vacuum herding the dog into the corner",
      "someone peering at the return policy through the plexiglass",
      "phone face-ID failing, then failing again, then one more time",
      "two people at the same table texting each other instead of talking",
      "AirTag chirping from inside the laundry pile",
      "the drone delivery hovering, reconsidering",
      "someone narrating their grocery run for an audience of twelve",
      "the password reset loop, three emails in",
      "cashier chasing a rolling apple",
      "dog wearing sunglasses in a stroller",
      "robot mop stuck under a chair leg",
      "someone bowing politely to the motion sensor trash can",
      "escalator handrail carrying one abandoned lettuce leaf",
      "someone scanning cilantro as parsley and accepting it",
      "automatic hand dryer starting for no hands",
      "man carrying a fully assembled lamp through the parking lot",
      "someone apologizing to the automatic paper towel dispenser",
      "grocery bag splitting exactly at the crosswalk",
      "barista spelling the name wrong twice",
      "someone stuck under a parking gate arm",
      "dog sitting in the shopping cart like a passenger",
      "someone scanning the same QR code from three different angles",
      "automatic soap dispenser launching soap onto a sleeve",
      "dog refusing to get out of the self-driving cart corral",
      "someone bowing at the automatic door that opened too late",
      "smart speaker pulsing blue while no one is in the room",
    ],
    sensory: [
      "the beep of the scanner that won't scan",
      "fluorescent light flickering in aisle seven",
      "new car smell in a very old car",
      "bubblegum stuck to the shoe",
      "the squeak of wet sneakers on the floor",
      "microwave popcorn smell in the office at 10am",
      "cold shopping cart handle",
      "the crinkling of someone opening candy very slowly in the quiet",
      "hot coffee in a too-thin paper cup",
      "the buzz of a phone on a hard table during a meeting",
      "elevator music, slightly too loud",
      "the clatter of a dropped pen rolling under every chair",
      "the triple notification sound from an unwatched tablet",
      "new shoe smell from the box on the couch",
      "the plastic crinkle of a package opened standing at the door",
      "the aggressive beep of a low battery at 2pm",
      "phone screen brightness blinding in a dark movie theater",
      "the tinny speakerphone voice filling the quiet waiting room",
      "hand sanitizer dispensed onto the counter, missed again",
      "the whirr of the label printer with one label left",
      "the lukewarm soup of the always-full condiment station",
      "mechanical keyboard clacking, one cube over",
      "the snap of a QR code menu loading too slowly",
      "cold plastic wrapper from the hotel TV remote",
      "receipt paper warm from the printer",
      "the squeal of a cart wheel",
      "soda fountain hiss in the quiet",
      "the sample toothpick snap in the food court quiet",
      "rubber gym mat smell and somebody's breakfast burrito",
      "receipt printer chirping like a distressed bird",
      "one rogue french fry smell in the office elevator",
      "freezer door fog blooming and clearing on the face",
      "free sample toothpick stuck to the sleeve",
      "hand dryer blasting the receipt into the sink",
      "cold fluorescent hum above the freezer door",
      "wet umbrella dripping into a metal tray",
      "the click of a receipt tearing",
      "self-checkout voice saying unexpected item while the scale is empty",
      "scanner beep echoing from three kiosks at once",
      "cold blast from the produce cooler at the worst possible moment",
    ],
    traces: [
      "passive-aggressive note on the office fridge",
      "someone left a single sock on top of the dryer",
      "googly eyes stuck on the fire extinguisher",
      "a tiny sweater on a tiny dog",
      "hand-written sign: this door is alarmed (it looks fine to me)",
      "lost cat poster, cat returned, poster still up",
      "sticky note on the monitor: you are doing great",
      "someone bedazzled the office stapler",
      "a cactus on a desk with a name tag",
      "out-of-order sign taped to the sign printer",
      "Wi-Fi password written on a napkin in a ziplock bag",
      "ring camera pointed directly at another ring camera",
      "a fake rock by the front door with a key inside it",
      "package decoy box on the porch to deter thieves",
      "phone mount on the dashboard, seven apps open",
      "sorry-for-any-inconvenience sign taped over another sign",
      "dating app open on the screen, face-down at brunch",
      "group chat screenshot printed and taped to the break room wall",
      "screen protector with one corner peeling since last February",
      "desk plant with a moisture sensor and a name tag",
      "sign says text to enter, no service inside",
      "the motion-activated air freshener that fires at everything",
      "handwritten Wi-Fi name and password on the fridge, in marker",
      "coffee ring under a paper cup",
      "lost and found bin with one mitten",
      "promo flyer wedged in the windshield crack",
      "staff-only sign held up by a cartoon cat sticker",
      "tap-to-pay symbol rubbed off from overuse",
      "smiley face added to the out-of-order sign",
      "loose googly eye in the shopping cart child seat",
      "QR code table tent stuck to yesterday's syrup",
      "coupon peeled off and stuck to the cart handle",
      "tiny sunglasses left in the dog park dirt",
      "finger smears on the glass door",
      "pizza box warped by steam",
      "scuffed toe mark on the elevator wall",
      "charging cable tied in a knot around a cafe table leg",
      "receipt with a smiley face and no total printed",
      "cart wheel squeal trail through spilled seltzer",
    ],
    absences: [
      "the other sock, last seen in the dryer",
      "the parking spot that was right there a second ago",
      "empty hook where the good pen used to be",
      "the matching tupperware lid, drawer full of orphans",
      "the grocery list, still on the kitchen counter",
      "the umbrella, home by the door, rain outside",
      "shopping cart with one wobbly wheel, chosen again",
      "the charger left in the other room",
      "the subscription nobody remembered to cancel, charged again",
      "the battery that died at 4% during directions",
      "the photo that didn't back up before the phone broke",
      "the reply drafted and never sent",
      "the item in the cart, out of stock at checkout",
      "the return window, closed yesterday",
      "the notification badge on the app nobody opens anymore",
      "the name of the restaurant saved somewhere on someone's phone",
      "the tab that had the thing open before the restart",
      "the earphone that went missing from the pair",
      "the confirmation email in the spam folder, found too late",
      "the coupon code that expired this morning",
      "the last cupcake in the box",
      "the friend who said be right back",
      "the price tag still on the shelf",
      "the cart token, still in yesterday's jeans",
      "the one screw left after the shelf stands up",
      "the quarter needed for the cart, every pocket linted but none",
      "the restroom code, on the receipt already in the trash",
      "the second Allen key everyone swore came in the box",
      "the one frozen blueberry that escaped at checkout",
      "the cart unlock quarter, committed to another cart",
      "the other glove in the coat pocket",
      "the one screw that rolled under the fridge",
      "the bike helmet missing from the hook",
      "the favorite tote bag, hanging on the doorknob at home",
      "the old phone in the drawer, charging port up",
      "the seat near the outlet taken by a coat and no person",
    ],
    turns: [
      "the grocery bag splitting at the crosswalk",
      "the card reader asking to try again",
      "the toddler running out of the frame",
      "the elevator doors closing on the wrong floor",
      "the dog lying down mid-walk and refusing",
      "the plastic chair leg catching the sidewalk crack",
      "the self-checkout freezing on the last item",
      "the automatic door staying shut, then opening after you step back",
      "the phone slipping out of the cup holder at the speed bump",
      "the straw wrapper unrolling across the table",
      "the ketchup packet bursting on the tray",
      "the cart wheel locking at the lot boundary",
      "the barcode scanner beeping at the ceiling",
      "the name called out, wrong person standing up",
      "the revolving door slowing for the person behind",
      "the paper receipt sticking to the wet counter",
      "the loyalty points expiring at checkout",
    ],
};
