// ── DOMESTIC-TURN (15%) ─────────────────────────────────────────
// Inside the home. Uses SCENE CLUSTERS because kitchen life,
// bedroom/night, and work/storage spaces have incompatible
// sensory details.

export const domesticTurn = {
    name: "domestic-turn",
    weight: 15,
    scenes: [
      // Cluster 1: Kitchen, dining, and common areas — cooking, eating,
      // packages, the living room, the front door
      {
        frames: [
          "kitchen counter, Tuesday evening",
          "dining table set for one",
          "kitchen sink, dishes soaking",
          "windowsill, afternoon sun",
          "front door, keys in hand",
          "kitchen counter, sourdough starter in a jar",
          "couch, third episode running",
          "front step, stack of packages",
          "kitchen, meal kit box half-unpacked",
          "living room, air purifier blinking red",
          "dining table, laptop shoved aside for dinner",
          "kitchen counter, robot vacuum docked and waiting",
          "living room floor, boxes half-packed",
          "back porch, last cigarette",
          "breakfast bar before dawn",
          "dish rack beside the open window",
          "entry table, mail fanned under the lamp",
          "kitchen island, groceries still in the app bags",
          "fridge door open at midnight, cold on the shins",
          "coffee table, unopened mail under the coasters",
          "entryway floor, grocery bags still sweating",
          "kitchen sink at dawn, dishwater gone cold",
          "kitchen island, cutting board and a half-peeled onion",
          "entry bench, boots lined toe to heel",
          "stove top, pan still warm under the lid",
          "balcony planter shelf, basil gone to seed",
        ],
        anchors: [
          "steam from the rice cooker fogging the window",
          "a faucet dripping into the quiet",
          "the kettle reaching its pitch",
          "plant leaning hard toward the window",
          "refrigerator compressor kicking on",
          "pilot light flickering blue",
          "soap bubble on the surface of the dishwater",
          "cat pushing a pen off the table edge",
          "smart speaker light pulsing blue in the empty kitchen",
          "robot vacuum circling the same chair leg",
          "sourdough starter bubbling in the jar on the counter",
          "delivery notification pinging, box already wet on the step",
          "air purifier filter light gone red",
          "meal kit ice pack sweating on the counter",
          "three streaming tabs open, none playing",
          "slow cooker lid on, doing its thing in the dark",
          "a door swinging shut on its own",
          "tea bag dripping into the mug",
          "banana browning in the bowl",
          "dishwasher soap pod dissolving behind the cloudy door",
          "key fob blinking from the bowl by the door",
          "microwave clock a minute fast again",
          "one app bag tearing open at the handles",
          "air fryer beeping into the empty room",
          "fridge light on the takeout container lids",
          "steam lifting off the pot lid",
          "toaster lever staying down",
          "ice tray cracking in the freezer",
          "range hood light flickering over the simmering pot",
        ],
        sensory: [
          "lemon peel and dish soap",
          "garlic browning, just before it burns",
          "vinegar and warm water on the counter",
          "toast smell drifting upstairs",
          "cold draft from the window that won't seal",
          "the click of the lock catching",
          "cardboard smell from the stack of broken-down delivery boxes",
          "air purifier hum steady behind every conversation",
          "meal kit spices still in their kraft paper envelopes",
          "single-serve coffee machine hissing through its pod",
          "the give of the couch nobody gets up from quickly",
          "cold delivery bag forgotten by the door",
          "sourdough tang filling the whole kitchen by noon",
          "candle wax cooling on the saucer",
          "onion steam on the glasses",
          "paper grocery bag crinkling open",
          "fried egg butter in the curtains",
          "recycling bin smell after the takeout night",
          "dish sponge souring by the sink",
          "screen door tapping in the draft",
          "dishwasher steam on the shins when the door cracks open",
          "orange peel drying on the cutting board",
          "warm dishwater on the wrists",
          "damp umbrella cloth and wet rubber",
          "garlic in hot butter",
        ],
        traces: [
          "height marks in pencil on the door frame",
          "recipe card in grandmother's handwriting, splattered",
          "scuff marks by the back door",
          "the dent in the couch cushion",
          "fridge magnet from a place they went once",
          "sourdough recipe laminated and taped to the fridge",
          "stack of flattened delivery boxes by the recycling bin",
          "workout log on the fridge, entries stopping in February",
          "bread flour dusted along the back of the counter",
          "the TV remote with tape holding the battery cover on",
          "the router login scratched in marker inside the cabinet door",
          "crumb line from counter to sink",
          "knife marks on the cutting board",
          "coupon magnet holding up the school photo",
          "grocery receipt tucked under the fruit bowl",
          "soy sauce ring under the takeout container",
          "coupon codes scribbled on the back of an envelope by the fruit bowl",
          "coupon codes stuck to the fridge with the dead magnet",
          "soy sauce packet box in the junk drawer, overfull",
          "bread crumbs in the grout line",
          "grease halo around the stove burner",
          "flour dust on the counter edge",
          "pizza coupon magnet layered over older takeout numbers",
        ],
        absences: [
          "empty hook beside the back door",
          "kitchen table with two chairs pushed in, two pulled out",
          "the mug with the chipped handle, still in the cabinet",
          "sourdough starter jar, lid on, in the back of the fridge",
          "the cookbook propped open on the counter, takeout on the table",
          "smart speaker, wake word dead, cord still in the outlet",
          "sourdough jar now holding pasta, label scratched off",
          "the second coffee mug rinsed and put back, one used",
          "one chair left pulled out",
          "dog bed cold and flat",
          "the takeout menu drawer, finally empty",
          "the house key missing from the hook with its label still there",
          "the place mat rolled up and put away",
          "the houseplant saucer dry and dusty",
          "the second place setting still stacked in the cabinet",
          "the takeout sauce drawer, almost all soy now",
          "the second chair pushed in and empty",
          "the bottle opener missing from the junk drawer",
          "the half-full spice rack with one gap",
          "the fruit bowl spot on the counter, ring of dust around it",
          "the second lunchbox hook by the pantry, label still taped on",
        ],
        turns: [
          "the doorbell, once",
          "the smoke detector chirping — just the battery",
          "a name called from another room",
          "the power flickering off, then back",
          "the front door opening downstairs",
          "a text arriving to an empty room",
          "the furnace cutting off, silence flooding in",
          "the sprinkler starting outside the open window",
          "the dog's nails on the floor, then nothing",
          "the last light turned off",
          "someone coming home, keys in the lock",
          "the dryer buzzer in the quiet house",
          "the front door latch clicking shut",
          "the refrigerator hum stopping",
        ],
      },
      // Cluster 2: Bedroom, bathroom, and hallway — night, sleep,
      // personal care, the spaces between rooms
      {
        frames: [
          "bedroom at 3am, wide awake",
          "bathroom mirror, morning",
          "hallway, nightlight on",
          "shower, water going cold",
          "nursery painted but empty still",
          "laundry pile on the bed",
          "bedroom floor, charging cables everywhere",
          "bathroom sink before sunrise",
          "nightstand under the reading lamp",
          "bathroom floor after the bath, towels underfoot",
          "hall closet, spare sheets on the top shelf",
          "hallway outside the bathroom, nightlight and towel heap",
          "dresser top before dawn, retainer case open",
          "bathroom counter, mouthguard soaking in a glass",
          "hallway at dawn, laundry basket against the wall",
          "bedroom door half shut, light under it",
          "hall closet, towels stacked on the shelf",
          "bath mat soaked flat by the tub",
        ],
        anchors: [
          "the iron cooling on the board",
          "clock hand moving, nothing else",
          "dust floating in the shaft of light",
          "a picture frame hanging slightly crooked",
          "thermostat clicking to a new setting",
          "phone screen lighting up face-down on the nightstand",
          "the washing machine entering its spin cycle",
          "dryer buzzing from the basement",
          "a child's shoe found behind the dryer",
          "toothbrush timer buzzing, nobody listening",
          "security camera light blinking green at the empty hallway",
          "shower curtain breathing inward",
          "hair clip on the nightstand",
          "retainer case left open by the sink",
          "nightlight catching the edge of a half-closed door",
          "humidifier light blinking blue beside the bed",
          "ceiling fan chain ticking the glass shade",
          "phone flashlight searching the floor for the dropped pill",
          "toothbrush charger light glowing beside the sink",
          "shower head dripping after shutoff",
          "medicine cabinet door not quite closed",
          "crib mobile turning in the draft",
        ],
        sensory: [
          "the hum of the house settling",
          "warm laundry against the face",
          "cold bathroom tile at 2am",
          "the weight of the comforter",
          "dust in the sunbeam",
          "clean sheets, still creased from folding",
          "the static on the blanket in the dark",
          "the particular silence of a house with sleeping children",
          "the white noise machine through the nursery door",
          "hand sanitizer smell lingering in the coat pocket",
          "the chirp of a low-battery smoke alarm, 3am",
          "old wood smell when the heat kicks on",
          "mint and hot water",
          "mirror fog on the cheeks",
          "lotion cooling on damp skin",
          "toothpaste mint in the warm hallway air",
          "shampoo steam gone lukewarm in the bathroom mirror",
          "elastic sheet corner snapping loose",
          "dryer sheet smell leaking under the bedroom door",
          "cool mirror edge against the knuckles",
          "cold tile under bare feet",
          "laundry soap in the hallway air",
          "night air through the cracked window",
        ],
        traces: [
          "stain on the ceiling from the upstairs leak",
          "tape residue where the poster was",
          "scratch on the floor from the furniture rearrangement",
          "ring on the nightstand from the water glass",
          "hook where the calendar hasn't been replaced",
          "charging cable worn through at the bend, taped over",
          "three different USB-C adapters in the catch-all bowl",
          "bobby pin in the drain stop",
          "single sock under the dresser",
          "pill bottle cap under the bed",
          "hair tie looped over the doorknob",
          "melatonin bottle cap under the nightstand",
          "lint roller with two sheets left on the dresser",
          "earplug pair in the nightstand dish",
          "face cream fingerprint crescents on the medicine cabinet mirror",
          "toothpaste smear on the sink rim",
          "towel fuzz on the tile",
          "shoe scuff on the hall wall",
        ],
        absences: [
          "the other side of the bed, made up tight",
          "crayon marks on the wall, painted over now",
          "the plant that didn't make it through the move",
          "the room with the closed door",
          "space where the bookshelf was, paint brighter there",
          "the gym bag by the door, zipped, no longer moving",
          "outlet strip full, nothing charging",
          "bathrobe hook empty",
          "calendar square left blank",
          "the second toothbrush cup, rinsed and dry",
          "the open drawer with one lens cloth and nothing else",
          "the charger block in the outlet, cable gone",
          "the pill organizer slot for Thursday, still full",
          "the humidifier tank, dry by morning",
          "the closet door that no longer clicks shut",
          "the second towel missing from the bar",
          "the medicine shelf with one gap",
          "the bedside lamp cord with no plug",
        ],
        turns: [
          "the smoke detector chirping — just the battery",
          "a name called from another room",
          "the power flickering off, then back",
          "the baby monitor crackling to life",
          "a text arriving to an empty room",
          "the sprinkler starting outside the open window",
          "the last light turned off",
        ],
      },
      // Cluster 3: Workspaces and storage — home office, garage,
      // attic, basement, spare room, garden shed
      {
        frames: [
          "garage workbench, Saturday",
          "storage closet, door half open",
          "attic, summer heat",
          "basement stairs, lightbulb out",
          "garden shed in the rain",
          "the junk drawer, pulled all the way out",
          "spare room with the treadmill nobody uses",
          "spare bedroom turned home office, midday",
          "home office desk, ring light on",
          "back bedroom, folded backdrop against the wall",
          "garage, two months of flattened delivery boxes",
          "standing desk folded against the wall",
          "garage workbench under a bare bulb",
          "basement shelf with winter coats boxed up",
          "utility shelf beside the water heater",
          "garage freezer, inventory list on the lid",
          "linen closet floor, flashlight between the towels",
          "garage shelf with the paint samples lined up",
          "garage shelf, return boxes sorted by tape color",
          "basement desk under the stairs, router lights blinking",
          "garage workbench, screws in a jar",
          "utility shelf beside the water heater, humming",
          "garage corner, bike wheel against the wall",
        ],
        anchors: [
          "paint roller marks drying on the wall",
          "a crack in the ceiling following a straight line",
          "ring light catching the dust on the shelf behind the chair",
          "laptop fan spinning up in the quiet room",
          "the router restarting, all the lights blinking in sequence",
          "standing desk motor whirring to the wrong height",
          "screwdriver beside three loose screws",
          "box cutter on the cardboard flap",
          "label maker spitting out one more strip",
          "motion light timing out over the workbench",
          "dehumidifier bucket light turning amber",
          "laser measure blinking across the spare room wall",
          "label maker jammed on the last letter",
          "printer feeding one page through the empty room",
          "drill battery on the charger light",
          "tape measure hanging open at the bench edge",
          "motion light fading over the shelf",
        ],
        sensory: [
          "the warmth of the laptop on the thighs at midnight",
          "blue monitor light in the otherwise dark room",
          "screen glare on reading glasses resting on the desk",
          "rubber mat smell from the unopened exercise equipment",
          "extension cord run under the rug to the middle of the room",
          "dry plaster dust in the nose",
          "cool concrete under bare feet",
          "metal ladder cold through the socks",
          "dusty cardboard smell when the bin comes down",
          "cold metal shelf smell and dust",
          "packing tape ripping too loud in the empty room",
          "mouse pad warmth under the wrist long after midnight",
          "paint thinner trace in the cold garage air",
          "sawdust in the nose",
          "cardboard glue and tape",
          "motor oil on the fingertips",
        ],
        traces: [
          "ring light bracket holes patched in the spare bedroom wall",
          "cable clips half-peeled off the desk edge",
          "blue painter's tape still marking the home office backdrop wall",
          "a row of sticky notes on the monitor bezel",
          "a ring of dried coffee from the mug that lived on the desk",
          "the before-and-after home improvement photo, project unfinished",
          "wrench outline in the dust",
          "box labels in thick black marker",
          "old Wi-Fi password crossed out on the sticky note",
          "paint can lid ringed with three dried colors",
          "instruction manual tucked in the toolbox drawer",
          "old return label still stuck to the storage bin",
          "return barcode printed and taped to the wrong box",
          "hex key taped inside the cabinet door",
          "paint swatches taped in a row",
          "tape outline on the floor where the shelf stood",
          "cable ties clipped to the pegboard",
        ],
        absences: [
          "the office chair returned, floor mat still there",
          "ring light still mounted, camera cord coiled below it",
          "the second monitor, unplugged, behind the door",
          "standing desk locked at sitting height, nobody standing",
          "router blinking in the otherwise empty room",
          "empty peg where the hammer hung",
          "shelf gap sized for a missing bin",
          "the folding table borrowed for the move, not back yet",
          "the storage bin labeled winter cords, shelf empty",
          "the extension cord hook, empty",
          "the foldout chair imprint in the carpet where the desk was",
          "the task chair wheel that rolled under the shelf",
          "the extension ladder spot in the garage, outline in dust",
          "the ladder spot on the garage wall",
          "the bike pump missing from the pegboard",
          "the tool drawer with one wrench slot open",
        ],
        turns: [
          "a car pulling into the driveway",
          "a name called from another room",
          "the power flickering off, then back",
          "a text arriving to an empty room",
          "the furnace cutting off, silence flooding in",
          "the dog's nails on the floor, then nothing",
          "the last light turned off",
          "the garage door going up",
          "the dryer buzzer in the quiet house",
          "the garage door rattling open",
        ],
      },
    ],
};
