// ── HUMAN-TRACE (20%) ──────────────────────────────────────────
// People in public/semi-public spaces. Uses SCENE CLUSTERS because
// the settings span very different physical spaces (hospital vs.
// bus vs. porch). Each cluster groups frames with compatible
// anchors, sensory details, traces, and absences.

export const humanTrace = {
    name: "human-trace",
    weight: 20,
    scenes: [
      // Cluster 1: Institutional interiors — waiting rooms, counters, hallways
      {
        frames: [
          "hospital hallway at shift change",
          "waiting room with the fish tank",
          "pharmacy counter, picking up the refill",
          "post office line, Wednesday afternoon",
          "auto shop waiting room",
          "dentist's office, staring at the ceiling tiles",
          "DMV, plastic chair, number not called yet",
          "urgent care, Sunday morning, no appointment",
          "social services office, forms on a clipboard",
          "courthouse hallway, metal detector behind",
          "blood draw lab, tissue paper on the table",
          "HR office, door closed",
          "radiology waiting room after lunch",
          "county clerk office, line at the counter",
          "county benefits office, last hour before closing",
          "outpatient lab, fasting since midnight",
          "MRI waiting area, lockers with keys on coils",
          "social security office, number called from a cracked speaker",
          "county clinic check-in desk, copier jammed again",
          "imaging center locker room, paper slippers in a stack",
          "pediatric clinic hall at shift change",
          "lab intake desk under the clock",
          "county vaccine clinic hallway, floor arrows half-peeled",
        ],
        anchors: [
          "nurse adjusting the blanket without waking anyone",
          "someone reading the same page over and over",
          "old man folding his newspaper very carefully",
          "child pressing face against the glass",
          "cashier counting down the drawer",
          "janitor mopping around the sleeping man",
          "receptionist watering the one plant on the counter",
          "security guard watching the door, not the screen",
          "someone filling out a form with a pen that won't write on the first stroke",
          "teenager scrolling without looking up when the name is called",
          "two strangers sharing the phone charger in the outlet by the baseboard",
          "intake worker asking the same question for the hundredth time today",
          "patient clutching a paper cup",
          "visitor holding a stack of discharge papers",
          "someone smoothing the carbon copy flat before signing",
          "clerk sliding the glass window open one inch",
          "someone flattening a wrinkled document against the wall",
          "clerk calling next and nobody stands up right away",
          "someone rebuttoning a shirt with one hand after the exam",
          "clerk flattening a wrinkled insurance card under the glass",
          "clerk stamping the form with a rubber stamp",
          "tech wheeling a cart of sealed specimens",
          "security guard untwisting a visitor badge lanyard for someone shaking",
        ],
        sensory: [
          "hand sanitizer sting",
          "the fluorescent hum",
          "paper rustling in the quiet",
          "the tick of the clock in the waiting room",
          "rubber sole squeak on the linoleum",
          "photocopy ink, faintly chemical",
          "cold from the plastic chair seeping through",
          "antiseptic mixing with someone's takeout",
          "the pressure change when the heavy door swings shut",
          "recycled air from a vent pointed at the neck",
          "low radio at the nurses' station, barely audible",
          "the muffled sound of the next room through the partition",
          "paper gown crackling",
          "the chirp of a badge reader",
          "burnt coffee from the staff room down the hall",
          "the cold of the metal armrest through a sleeve",
          "printer toner warm from the copier alcove",
          "cold water from the fountain tasting faintly metallic",
          "the drag of the pen chain across the laminate",
          "microwave soup from the staff room leaking into the hallway",
          "copy room toner warming the air",
          "heavy door seal thumping shut",
          "chair vinyl sticking to the backs of the knees",
        ],
        traces: [
          "dog-eared page in the waiting room magazine",
          "name tag that says trainee",
          "worn spot on the railing where everyone grabs",
          "umbrella in the lost and found, months now",
          "hand-lettered hours sign, the s backwards",
          "sticky note on the microwave: please clean up after yourself",
          "QR code sign taped to the wall, corner peeling",
          "hand sanitizer dispenser mounted at an odd angle, never quite right",
          "number ticket torn and left on the floor",
          "out-of-date pamphlets fanned on the table",
          "tape outline on the floor where a chair was removed",
          "coffee ring on the intake clipboard",
          "wheelchair scuff on the baseboard",
          "blue pen chained to the clipboard, cap chewed flat",
          "visitor badge sticker stuck to the underside of the chair",
          "mask loops tucked under the chair leg",
          "appointment reminder text printed and folded in a wallet",
          "clipboard corner darkened by hundreds of thumbs",
          "insurance card photocopy left face down in the tray",
          "rolled ticket under the chair leg",
          "strip of blue tape on the floor",
          "intake clipboard with the old logo stickered over",
        ],
        absences: [
          "the chair at the table nobody sits in",
          "reading glasses on the nightstand, prescription outdated",
          "half-finished crossword on the counter",
          "the fish tank with one fewer fish than last time",
          "the second service window, glass dim inside",
          "the courtesy phone unplugged and pushed to the wall",
          "the row of chairs taken out for distancing, never returned",
          "the name on the intake form, crossed out and rewritten",
          "the water cooler, jug empty",
          "the pager that stopped buzzing",
          "the fish tank bubbler off for the day",
          "the interpreter phone dock empty at the desk",
          "the children's corner rug, outline still darker on the floor",
          "the interpreter handset cradle, empty",
          "the charging outlet by the chair, cover plate hanging open",
          "the volunteer at the information desk, coat still on the hook",
          "the second receptionist station dark",
          "the lobby fish tank without bubbles",
          "the extra blood pressure cuff hook, velcro strap still hanging",
          "the walker parking bay tape marks with no walkers in line",
        ],
        turns: [
          "a name called from the desk",
          "the automatic door opening for no one",
          "the intercom, garbled, meaning unclear",
          "someone standing up to leave mid-wait",
          "the lights flickering once",
          "the number on the screen changing",
          "a phone ringing behind the closed door",
          "the copier starting on its own",
          "someone's alarm going off in their bag",
          "the elevator arriving empty",
          "the waiting room TV changing channels",
          "a clipboard handed back, something circled",
          "the receptionist looking up from the screen",
          "the clerk calling the next name",
        ],
      },
      // Cluster 2: Service and retail — laundromats, diners, shops, libraries
      {
        frames: [
          "laundromat, last load spinning",
          "barber shop, last appointment",
          "library, five minutes to closing",
          "diner booth, window seat",
          "thrift store dressing room",
          "grocery store at closing time",
          "phone repair shop, waiting for the screen",
          "nail salon, under the UV lamp",
          "copy shop at midnight, thesis due",
          "pawn shop, items in the glass case",
          "pet store after the crowd thins out",
          "corner bookstore, rain on the glass",
          "bakery counter before opening",
          "tailor shop, hem chalk still on the cuff",
          "corner deli, lottery screen humming",
          "nail salon after the last pedicure chair drains",
          "print shop pickup counter, posters still warm",
          "dry cleaner counter, claim ticket in hand",
          "corner bodega at midnight, mop bucket by the chips",
          "coin laundry with the front door propped open",
          "bakery prep table at 4am",
        ],
        anchors: [
          "woman laughing alone at her phone",
          "teenager drawing in the margin of a textbook",
          "someone mouthing words to the song on their earbuds",
          "cook eating alone at the bar after closing",
          "mechanic wiping hands on a rag already dirty",
          "grandmother braiding hair, not looking up",
          "someone choosing between two nearly identical cans",
          "repair technician peeling back a cracked screen with a spudger",
          "delivery driver picking up four orders at once, bags balanced up the arm",
          "librarian re-shelving, reading each spine before it disappears",
          "customer service rep with headset on, making a face no one can see",
          "someone photographing a price tag to check it online first",
          "barista wiping the steam wand",
          "seamstress pinning a hem",
          "someone testing the zipper twice before buying",
          "cashier straightening the gum rack with one finger",
          "tailor snipping one loose thread and holding it up",
          "cashier sliding the plexiglass window open with one knuckle",
          "cashier peeling coins from the till with one thumb",
          "someone testing the reading glasses from the spinner rack",
          "seamstress chalking a hem on denim",
          "repair tech lining up screws on a magnet tray",
        ],
        sensory: [
          "dryer sheet smell through the vent",
          "floor wax and coffee",
          "warm vinyl under the thighs",
          "the give of a foam seat cushion",
          "soap smell on clean hands",
          "pen clicking, someone nervous",
          "the weight of keys in the pocket",
          "hair dryer heat drifting from the back room",
          "old paperback smell in the used section",
          "the whirr of the laminator heating up",
          "bergamot from the candles no one buys",
          "card reader beep, then silence waiting for approval",
          "espresso steam and lemon cleaner",
          "receipt paper curling in the heat",
          "warm air from the back room when the door swings open",
          "floor cleaner drying at the threshold",
          "bleach from the laundromat drain and sugar glaze from next door",
          "refrigerated case starting up with a low shudder",
          "warm dust from the refrigerator coils by the soda case",
          "plastic garment bag crackling at the dry cleaner",
          "dryer heat and detergent foam",
          "glass case cooling the fingertips",
        ],
        traces: [
          "a shopping list in someone else's handwriting",
          "lipstick print on the coffee cup lid",
          "kid's drawing on the fridge at the repair shop",
          "someone left a reusable bag on the counter",
          "quarter taped to the vending machine for the next person",
          "a photo taped inside the locker door",
          "contactless sticker over the old card slot",
          "price gun left on the shelf with one roll of stickers out",
          "employee of the month photo where the frame faded",
          "coffee ring on the order pad",
          "loyalty card punched eleven times, never redeemed",
          "taped coupon on the register",
          "lost mitten on the shelf end",
          "alterations ticket pinned to the sleeve",
          "library receipt used as a bookmark in the cookbook aisle",
          "alteration pins caught in the shop carpet",
          "take-a-number dispenser empty, tickets curled in the tray",
          "hem chalk dust on the fitting stool",
          "reward card key tag left on the card reader",
          "shopping basket with one broken handle",
          "seam chalk dust on the stool rung",
        ],
        absences: [
          "coat still on the hook, owner gone",
          "lunch brought for two, eaten alone",
          "the dog's bowl, dry for a week",
          "second coffee cup rinsed and put back",
          "the landline on the counter, cord dangling",
          "the tip jar, empty by close",
          "the seat at the counter he always took",
          "section closed, chairs flipped, one still down",
          "the shop cat gone from the window",
          "the last pastry tray scraped clean",
          "the second stool at the lunch counter, tucked in",
          "the bell over the shop door, silent between customers",
          "the fitting room hook with one empty hanger",
          "the library hold shelf gap with the name slip still there",
          "the spinning rack of postcards with one town missing",
          "the repair ticket hook with one tag still clipped",
          "the fitting room curtain half closed with nobody inside",
          "the return cart parked and silent",
        ],
        turns: [
          "the automatic door opening for no one",
          "someone standing up to leave mid-wait",
          "the lights flickering once",
          "a child let go of the hand",
          "someone's alarm going off in their bag",
          "the clerk calling the next name",
          "the receipt printer spitting a strip",
          "the cart wheel squeaking past the door",
        ],
      },
      // Cluster 3: Thresholds and passages — porches, stairwells, lobbies, parking lots
      {
        frames: [
          "porch steps after everyone left",
          "elevator between floors",
          "hotel hallway at 2am",
          "parking lot, sitting in the car a minute longer",
          "stairwell of the old apartment",
          "school hallway, summer break",
          "building lobby, waiting for the delivery buzzer",
          "fire door propped with a brick, smoking area",
          "apartment entryway, shoes piled by the door",
          "loading dock, smoke break, leaning on the rail",
          "hospital corridor, between the ward and the exit",
          "parking garage stairwell, footsteps echoing",
          "apartment stoop in the drizzle",
          "parking deck exit ramp",
          "mailroom after the package rush",
          "apartment vestibule, rain drying on the mat",
          "apartment hallway after the grocery delivery rush",
          "front stoop under the package locker camera",
          "package room, fluorescent after midnight",
          "apartment stair landing, takeout smell still there",
          "office vestibule before the buzzer",
          "parking ramp corner by the pay station",
        ],
        anchors: [
          "someone holding a door for no one coming",
          "someone waving at the wrong person",
          "crossing guard waving at the last car",
          "father teaching a child to tie shoes on the lobby bench",
          "security guard reading a paperback",
          "dog walker untangling three leashes at the gate",
          "courier photographing the doorstep before riding off",
          "two people sharing a doorway out of the rain, strangers",
          "person standing in the lobby on a video call, screen lighting the face",
          "someone propping the elevator with a foot, arms full of bags",
          "child pressing every button in the elevator, parent too tired",
          "courier juggling three boxes at the buzzer",
          "someone pausing on the landing to catch breath",
          "neighbor balancing groceries on one knee for the key fob",
          "someone checking the unit number twice in the dim hall",
          "neighbor setting the grocery bag down to catch breath",
          "elevator mirror briefly full of no one",
          "someone checking the mail slot twice with empty hands",
          "door closing on the grocery cart wheel, then bouncing back",
          "courier scanning a package at the threshold",
          "person wiping rain off the keypad with a sleeve",
        ],
        sensory: [
          "cold tile through thin socks",
          "the particular warmth of a phone in the palm",
          "static from pulling off the sweater",
          "the weight of keys in the pocket",
          "stale air and old carpet",
          "the echo of footsteps in the empty hallway",
          "cold metal handrail under the palm",
          "exhaust smell from the idling rideshare",
          "the vibration of the phone against the hip, wrong notification",
          "grease smell from the kitchen exhaust above the back entrance",
          "the hiss of the automatic door sensor triggering on nobody",
          "pavement heat rising through the soles",
          "cold brass latch",
          "wet umbrella dripping on the tile",
          "wet concrete smell from the parking ramp",
          "door closer sighing shut behind you",
          "hallway heat trapped under the stairwell skylight",
          "wet cardboard smell from packages left by the mailboxes",
          "rain jacket drip at the heel on the concrete landing",
          "cool draft coming up through the stairwell gap",
          "stairwell echo under bare walls",
          "package tape sticking to the fingers",
        ],
        traces: [
          "worn spot on the railing where everyone grabs",
          "a photo taped inside the locker door",
          "sticker residue on the mailbox",
          "someone's initials in the concrete, edges rounded",
          "taped-over doorbell",
          "faded welcome mat, letters nearly gone",
          "ring doorbell camera, small red light always on",
          "package slip tucked under the mat, second notice",
          "scooter left blocking the ramp, slightly askew",
          "hand sanitizer dispenser at the entrance, empty",
          "door hinge painted over too many times, sticky now",
          "delivery sticker on the buzzer panel",
          "paint worn off the stair edge",
          "takeout menu tucked in the corner of the lobby mirror",
          "parcel locker door hanging open, empty",
          "boot tray full of dried salt at the vestibule door",
          "paper notice curling on the lobby bulletin board",
          "parcel locker code written on the back of a receipt",
          "takeout sauce packet burst under the mailroom bench",
          "door jamb nicked by a cart wheel",
          "finger marks around the buzzer plate",
        ],
        absences: [
          "pair of boots by the door, laces still tied",
          "garden gloves stiff on the shelf",
          "voicemail light blinking on the old phone",
          "the apartment number, still on the directory downstairs",
          "the doorman's stool, nobody there since the renovation",
          "the intercom panel with half the names scratched off",
          "the neighbor you waved to every morning, moved now",
          "the peephole dark from the other side",
          "the cab that never turned up",
          "the light in the stairwell, burned out",
          "the holiday wreath hook, bare now",
          "the elevator display stuck on a floor nobody is on",
          "the apartment buzzer label, peeled off clean",
          "the stairwell mirror taken down, hooks left behind",
          "the hallway runner rug rolled up after the leak",
          "the name card slipped out of one buzzer slot",
          "the mail key missing from the hook",
          "the call button with no light",
        ],
        turns: [
          "the lights flickering once",
          "a child let go of the hand",
          "someone's alarm going off in their bag",
          "the elevator arriving empty",
          "the parking meter expiring",
        ],
      },
      // Cluster 4: Digital-age spaces — coworking spaces, coffee shops with laptops, ring lights, podcast setups
      {
        frames: [
          "coworking space, hot desk by the window",
          "coffee shop, every seat a laptop screen",
          "phone repair counter, cracked glass in a tray",
          "podcast studio, foam panels on every wall",
          "content creator's bedroom, ring light on a stand",
          "library study pod, soundproofing foam visible",
          "airport lounge, outlet strip fully occupied",
          "shared office common area, someone on a standing call",
          "video call taken from the car in the parking lot",
          "live streaming setup in a spare bedroom, blackout curtains",
          "tech startup open plan, plants and whiteboards",
          "maker space with microphones on the table",
          "garage studio, green screen wrinkled",
          "shared office phone booth, ring light folded in the corner",
          "coffee shop bar seat, charging brick warm",
          "shared office kitchen, everyone taking calls from the hallway",
          "podcast editing desk, waveform frozen on the second monitor",
          "coffee shop window bar, laptop webcam taped over",
          "shared office phone booth, reservation expired two minutes ago",
          "meeting room with camera tripod by the wall",
          "studio corner with a mic arm and pop filter",
        ],
        anchors: [
          "ring light catching in someone's glasses across the cafe",
          "person on a video call, one AirPod in, nodding at the screen",
          "gig worker checking two phones at once between deliveries",
          "content creator filming a coffee pour from three inches away",
          "phone repair tech peeling a cracked screen with a suction cup",
          "someone in a podcast booth laughing at something no one else hears",
          "laptop sticker collection viewed from behind on the train",
          "cursor blinking on a blank document for the last twenty minutes",
          "three screens open, all showing different versions of the same thing",
          "delivery notification appearing on the watch mid-meeting",
          "webcam glow on the face in the phone booth glass",
          "phone propped against a salt shaker to film a meal",
          "moderator muting a noisy mic",
          "someone waiting for the upload bar to move",
          "someone rehearsing into the webcam before unmuting",
          "tablet propped against the sugar jar, comments scrolling",
          "someone angling the ring light away from the unmade bed",
          "courier scanning a pickup while still on mute",
          "someone rehearsing a smile in the black webcam window",
          "courier plugging into the only free outlet without sitting down",
          "person muting and unmuting the mic",
          "someone taping paper over the camera light",
        ],
        sensory: [
          "mechanical keyboard clicking in waves across the open floor",
          "white noise machine at the phone repair counter",
          "ring light warmth on the forehead",
          "the low sustained hum of too many chargers",
          "oat milk and espresso smell under the ventilation draft",
          "earbud foam, slightly warm, pulled from the case",
          "the rubbery give of a new phone case being fitted",
          "camera fan whine",
          "warm charging cable in the hand",
          "fan heat off the laptop hinge",
          "the sticky feel of the conference room mic cover",
          "old espresso grounds warming on the cafe machine",
          "laptop exhaust warming the wrists at the hot desk",
          "fingerprint-smudged phone glass warming under the ring light",
          "the stale heat of a laptop sleeve left in the sun",
          "charger heat in the palm",
          "screen glow on the forearms",
        ],
        traces: [
          "cable management velcro on every desk, still not enough",
          "QR code sticker on the table for the cafe wifi",
          "sticker residue on the laptop lid, faint square outline",
          "ring light tripod marks on the carpet",
          "row of charging cables labeled with tape and initials",
          "used PopSocket stuck to the counter, left behind",
          "ring light mark on the tabletop",
          "password scribbled on masking tape",
          "blue light glasses folded on the standing desk mat",
          "webcam privacy slider cracked but still in place",
          "gaffer tape X on the floor for the camera tripod",
          "mute reminder sticky note on the monitor frame",
          "sanitizer streak dried across the phone repair counter",
          "sticky residue from a conference badge on the laptop lid",
          "tape X on the floor for the tripod",
          "webcam cover slid halfway shut",
        ],
        absences: [
          "the landline on the wall, jack painted over",
          "the desk with the monitor still on, chair tucked in",
          "the office that became a podcast room",
          "the webcam cover slid shut",
          "the desk chair turned away from the screen",
          "the whiteboard wall wiped clean except one timestamp",
          "the second headset hanging unused on the hook",
          "the second stool outside the podcast booth, headphones coiled and unused",
          "the bookshelf turned backwards for the video background",
          "the analog wall clock hidden behind the acoustic panels",
          "the notebook opened for the meeting, page still blank",
          "the second headset on the hook",
          "the spare monitor unplugged",
        ],
        turns: [
          "the lights flickering once",
          "a phone ringing behind the closed door",
          "the copier starting on its own",
          "someone's alarm going off in their bag",
          "the elevator arriving empty",
        ],
      },
      // Cluster 5: Medical and clinical care — vet, clinic, PT, hospice, school nurse
      {
        frames: [
          "vet's waiting room, carriers on every chair",
          "physical therapy gym, parallel bars and mirrors",
          "hospice common room, afternoon light",
          "free clinic, Saturday morning",
          "school nurse's office, cot with paper sheet",
          "animal shelter intake desk, leash on the counter",
          "memory care unit, activity room",
          "dialysis waiting room before sunrise",
          "veterinary exam room, scale by the door",
          "oncology infusion room, warmed blankets in a cabinet",
          "school nurse doorway, ice packs stacked in a bin",
          "rehab clinic waiting room, resistance bands in a basket",
          "animal shelter hallway, stainless bowls stacked by the sink",
          "infusion bay with blanket stacks",
          "x ray alcove with lead apron hooks",
        ],
        anchors: [
          "dog pressing its nose hard into the carrier grate",
          "physical therapist counting reps out loud, the patient mouthing along",
          "cat yowling once and then silent the entire waiting room",
          "child drawing on the exam table paper while the parent fills out the form",
          "aide holding an elderly woman's hand through a TV show",
          "someone's hands shaking while signing the intake form",
          "physical therapy band snapping back to the hook",
          "student nurse peeling the backing off a fresh name label",
          "therapy dog leaning against a shin and not moving",
          "someone folding the discharge socks into a coat pocket",
          "someone folding discharge papers into quarters and unfolding them again",
          "technician shaking treats into a paper cup outside the exam room",
          "technician weighing a cat in a towel",
          "patient tracing the bandage edge with a thumb",
        ],
        sensory: [
          "dog fur and antiseptic mixed together",
          "the squeak of sneakers on a rehabilitation gym floor",
          "folding chair cold through thin pants",
          "hand sanitizer and floor wax in the corridor",
          "the particular hush of a hospice hallway",
          "exam paper cool against the backs of the legs",
          "the soft whine of the automatic blood pressure cuff",
          "orange cleaner on the PT mats",
          "paper cup of water sweating on the tray table",
          "laundered blanket warmth from the cabinet",
          "dog nails skittering once on the polished floor",
          "antiseptic and wet fur",
          "low refrigerator hum from the meds fridge",
        ],
        traces: [
          "pill organizer labeled in a caregiver's handwriting",
          "leash hanging on the vet's hook, collar still attached",
          "crayon drawing on the waiting room chair from a previous visit",
          "the name band cut off and left on the nightstand",
          "paw print sticker stuck to the file folder",
          "walker tennis balls worn gray at the bottom",
          "intake sticker stuck to the heel of a sneaker",
          "hearing aid battery pack in the bedside drawer",
          "paper collar from the therapy band still around the wrist",
          "walker parked with a tote bag hooked to one handle",
          "cat hair on the scale mat",
          "discharge packet folded and refolded",
        ],
        absences: [
          "the pet carrier, returned without the pet",
          "the small bed in the corner, stripped and waiting",
          "the name on the chart, room reassigned",
          "the kennel tag on the hook, no leash beneath it",
          "the extra blanket folded at the foot of the recliner, untouched",
          "the wheelchair footrests swung up, chair unoccupied",
          "the volunteer cart parked with no magazines left",
          "the folding screen pulled back, exam stool still warm",
          "the name written on the whiteboard, wiped away except the first letter",
          "the blanket in the warmer untouched",
          "the pet tag on the hook with no collar beneath",
        ],
        turns: [
          "a name called from the desk",
          "the intercom, garbled, meaning unclear",
          "someone standing up to leave mid-wait",
          "the lights flickering once",
          "the number on the screen changing",
          "a phone ringing behind the closed door",
          "someone's alarm going off in their bag",
          "the elevator arriving empty",
          "the waiting room TV changing channels",
          "a clipboard handed back, something circled",
          "the receptionist looking up from the screen",
          "the cart wheel squeaking past the door",
        ],
      },
      // Cluster 6: Community care — daycare, food bank, community fridge, group therapy
      {
        frames: [
          "daycare pickup line, 5:15pm",
          "group therapy circle, metal folding chairs",
          "food bank line, Tuesday distribution",
          "community fridge on the sidewalk, door ajar",
          "after-school program, gym converted to homework tables",
          "mutual aid table on the church steps, sorted by need",
          "soup kitchen serving line, noon",
          "school gym set up for donations",
          "school pickup shelter in the drizzle",
          "community pantry shelf after the rush",
          "community pantry restock hour, folding table by the curb",
          "daycare cubbies at closing, construction paper still taped up",
          "after-school snack table, apple slices going brown",
          "community fridge restock in the dark, porch light overhead",
          "school cafeteria with food bank tables",
          "family resource office with diaper shelves",
        ],
        anchors: [
          "child running across the daycare lot and stopping just short",
          "someone in the therapy circle passing the tissue box without being asked",
          "volunteer stacking canned goods by expiration date",
          "stranger arranging donated food in the community fridge carefully",
          "volunteer writing names on bagged lunches in marker",
          "volunteer handing over a bag with both hands",
          "neighbor labeling freezer meals with a marker",
          "volunteer matching lone gloves into pairs",
          "someone adding two clementines to every bag",
          "teacher kneeling to zip the last small coat",
          "volunteer counting diapers into clear bags",
          "volunteer counting out bus passes beside the granola bars",
          "teacher shaking sand from a child's rain boot into the trash",
          "volunteer pairing mittens by size",
          "child choosing one apple and putting back the bruised one",
        ],
        sensory: [
          "baby wipe smell at the pickup counter",
          "hand lotion and coffee from the volunteer's cart",
          "cardboard box smell and cold air from the open fridge door",
          "crayons and floor cleaner in the after-school room",
          "the metallic clink of folding chairs",
          "hot coffee from a donated thermos",
          "radiator heat and wet mitten smell by the daycare door",
          "marker squeak on the paper lunch sack",
          "banana box cardboard and canned tomato smell",
          "dry-erase marker and wet pavement at pickup",
          "orange peel and wet mitten smell by the cubbies",
          "freezer frost breath from the community fridge door",
          "wet wool from the coat pile",
          "cold air spilling from the fridge door",
        ],
        traces: [
          "child's height chart taped to the daycare doorframe",
          "name written on a paper bag in a volunteer's careful block letters",
          "a note in the community fridge: made with love, gluten free",
          "sign-in sheet with the same names every week",
          "names crossed off on a clipboard",
          "tally marks on the donation board",
          "zip-top bags of crayons sorted by color",
          "cooler lid labeled yogurt only in block letters",
          "donated mittens clipped together with clothespins",
          "pickup sign with old phone numbers crossed out",
          "thank-you card taped to the donation bin with purple marker hearts",
          "roll of name stickers half used on the folding table",
          "folded route maps on the table",
          "lunch sacks lined in a crate",
        ],
        absences: [
          "the chair left empty in the circle",
          "the name on the pickup list, no one came for yet",
          "the donation bin, emptied faster than it filled this week",
          "the last loaf taken before close",
          "the spare chair nobody claimed",
          "the cubby with the family photo still taped inside",
          "the last gallon of milk, space still cold",
          "the shelf space where diapers go first",
          "the next week's sign-up sheet, all blank",
          "the last winter coat on the rack, size too small for anyone here",
          "the milk crate where bananas go first",
          "the cold shelf where bread went first",
          "the lunch bag with no name tag",
        ],
        turns: [
          "the lights flickering once",
          "a child let go of the hand",
          "someone's alarm going off in their bag",
          "a name called from the desk",
        ],
      },
    ],
};
