// ── OBSERVATION (30%) ───────────────────────────────────────────
// Outdoor stillness, nature watched closely. All entries are
// plausible in the same class of outdoor/edge-of-nature settings.

export const observation = {
    name: "observation",
    weight: 30,
    scenes: [
      // Cluster 1: quiet-outdoors — woods, trails, park benches, wooded paths,
      // field edges, fishing piers, birding spots, orchards, meadows, clearings
      {
        frames: [
          "park bench after rain",
          "trail head, first light",
          "cemetery path in October",
          "hilltop above the fog line",
          "field edge where the mowing stopped",
          "meadow after the first mow",
          "overlook point, nobody else there",
          "solar charging station at a trailhead, mid-morning",
          "EV charging bay at the edge of a state park",
          "e-scooter dock at the park entrance, three left",
          "wildlife camera strapped to the pine, blinking red",
          "observation deck above the wetlands, boardwalk swaying",
          "trailhead kiosk with the glass cracked",
          "mountain hut solar panel rattling in the wind",
          "bird hide with the narrow slot window",
          "picnic table at the edge of the burn zone",
          "quarry rim path, the far wall still echoing",
          "dune crossing, the wind erasing the path",
          "picnic shelter after the hailstorm",
          "orchard edge after the first frost",
          "overflow parking at the trailhead, one car left",
          "floodplain trail after the river dropped",
          "fire road along the ridge",
          "old fire tower spur, locked gate, ravens overhead",
          "service road behind the cell tower, milkweed gone to fluff",
        ],
        anchors: [
          "spider web catching first light",
          "shadow of a cloud crossing the field",
          "hawk circling without flapping",
          "bee entering a clover blossom",
          "moss spreading across the stone",
          "mushroom pushing through the mulch",
          "moth resting on the screen door",
          "cat sitting perfectly still in the window",
          "rabbit frozen in the grass",
          "squirrel frozen mid-step on the rail",
          "drone sound fading over the ridgeline",
          "AirPod on the trail, one, no case",
          "deer sniffing the solar panel post",
          "trail camera blinking at the empty path",
          "raven watching from the trail sign",
          "marmot standing at the entrance to its hole",
          "weed growing through the cracked trailhead map",
          "turkey vulture landing on the trail camera pole",
          "feather stuck in the chain-link fence",
          "cicada shell on the fence post",
          "fern frond uncurling beside the path",
          "garter snake crossing the warm gravel",
          "killdeer limping ahead on the gravel shoulder",
          "swallowtail drinking from the damp tire rut",
          "vole trail threading the frost on the meadow edge",
          "lizard doing push-ups on warm stone",
        ],
        sensory: [
          "wet earth smell after thunder",
          "wind shifting direction",
          "dry grass clicking in the breeze",
          "distant lawn mower drone",
          "cold from the stone seeping through",
          "sun warming one side of the face",
          "the quiet after a plane passes",
          "dew soaking through canvas shoes",
          "bark rough under the palm",
          "pine sap sticky on the railing",
          "the sharpness of cedar",
          "the softness of lichen",
          "cloud shadow cooling the skin",
          "hot plastic smell of a sun-warmed trail marker",
          "the creak of the solar panel frame expanding",
          "gravel dust settling on the sun-warmed phone screen",
          "bluetooth speaker sound bleeding from the next campsite",
          "generator hum from the trail shelter",
          "resin smell from pine needles on hot asphalt",
          "cold from the aluminum water bottle through the pack",
          "exhaust smell disappearing as the trailhead parking clears",
          "sandpaper rasp of lichen under the fingertips",
          "thunderstorm building, ozone before the first drop",
          "the buzz of a trail camera motion sensor triggering",
          "mud suction at each step",
          "cold metal of the trail sign",
          "mosquito whine near the ear",
          "juniper smell lifting off the sun-warmed slope",
          "cold bench slat through the jacket",
          "midges ticking against the sunglasses",
          "trail dust sticking to sunscreen on the forearms",
          "cold zipper pull against the lower lip in wind",
          "sweet rot of cottonwood buds in warm rain",
        ],
        traces: [
          "initials carved into the bench",
          "worn patch in the grass where people cut the corner",
          "bird feeder swinging empty",
          "kite string caught in the oak",
          "stone stack someone balanced by the creek",
          "faded no trespassing sign",
          "tent stake in the ground, no tent",
          "trail register entry three weeks old, last one",
          "gel packet wrapper in the cairn stones",
          "orange mesh fencing around the revegetation patch",
          "QR code trail map on the post, faded",
          "bear canister left on the register table",
          "spent glow stick in the fire ring",
          "drone landing pad spray-painted on the flat rock",
          "charge cable coiled on the trailhead bench",
          "laminated prayer card tied to the summit cross",
          "reflective blaze nailed to a dead tree",
          "campfire ring rebuilt by each new group, slightly off center",
          "solar light stuck in the ground by the pit toilet",
          "wildlife crossing sign with the deer silhouette shot through",
          "plastic bag tied to the trailhead gate: trail closed, use map",
          "orange survey ribbon tied to a branch tip",
          "camp chair imprint in the flattened grass",
          "bench plaque green at the screws",
          "granola crumbs in the trail map kiosk",
          "zip tie tail left on the new park sign",
          "torn map corner in the kiosk",
          "branch tied back with twine",
          "phone tripod footprint pressed into the wet overlook soil",
          "trail crew chalk mark on a rock, half washed away",
          "sun-bleached map pin still stuck in the kiosk cork",
          "broken sunglass arm beside the trail register",
        ],
        absences: [
          "the bird that was just singing",
          "bench where someone sat long enough to wear it smooth",
          "hole in the hedge where something pushed through",
          "the space a fallen tree opened in the canopy",
          "nest with no eggs",
          "web with no spider",
          "worn groove in the stone steps, no one climbing",
          "the signal bar that was there at the last switchback",
          "the bear box, padlock open, empty",
          "the sound of other hikers, gone since the split in the trail",
          "fire lookout tower, stairs removed, access closed",
          "the blaze on the tree, bark grown around it now",
          "snow on the pass in August — not this year",
          "the wolf that crossed here, prints filling with rain",
          "the trail section rerouted around the gravel lot",
          "the elk the ranger said to watch for",
          "the pull station on the trail kiosk, snapped off",
          "path without footprints",
          "the map behind the kiosk glass, sun-bleached to nothing",
          "the second chair at the overlook, only rust marks left",
          "the ranger map box, brochures gone by noon",
          "branch scar where the nest hung",
          "empty feeder pole in the grass",
          "the nesting box door hanging open, no swallows this season",
        ],
        turns: [
          "the wind changing direction",
          "a branch cracking somewhere above",
          "the bird going quiet",
          "a dog barking once across the valley",
          "the shadow reaching the bench",
          "a car door slamming in the parking lot",
          "the hawk folding its wings",
          "the trail runner passing without looking up",
          "the last light leaving the treeline",
          "the temperature dropping with the cloud",
          "the gate banging shut behind",
          "a plane crossing the gap in the clouds",
          "a flock lifting at once",
          "the wind dropping flat",
        ],
      },
      // Cluster 2: edge-of-civilization — abandoned tennis courts, vacant lots,
      // bus stops, industrial edges with weeds, parking-lot margins,
      // strip-mall fringes, back alleys, fence lines
      {
        frames: [
          "bus stop at dusk",
          "bridge overpass, mid-afternoon",
          "empty parking lot, Sunday morning",
          "rooftop at golden hour",
          "fire escape, three floors up",
          "rest stop off the highway",
          "train platform between trains",
          "baseball diamond in winter",
          "churchyard at noon",
          "gravel road shoulder",
          "abandoned tennis court, net sagging",
          "gravel pullout where the cell signal returns",
          "highway sound barrier, weeds growing at the base",
          "farm road ditch after rain",
          "creek crossing under the highway bridge",
          "culvert mouth in the weeds",
          "boat ramp parking lot, geese taking over the painted lines",
          "water treatment outfall trail, mist rising in the cold",
        ],
        anchors: [
          "crow landing on a wire",
          "dandelion seed drifting over the fence",
          "dragonfly hovering above the puddle",
          "ant carrying something twice its size",
          "raindrop hanging from a branch tip",
          "icicle dripping in the sun",
          "pigeon drinking from a gutter stream",
          "butterfly landing on a rusted hinge",
          "crow pulling at the tied garbage bag",
          "tick crawling across the back of the hand",
          "phone screen catching the sun from the ground",
          "hummingbird pausing at the red NO PARKING sign",
          "dog nose pushing through the chain-link gate",
          "orb-weaver web strung between two gate posts",
          "swifts cutting under the overpass",
          "paper wasp drinking from the edge of a puddle",
          "e-scooter half-submerged at the creek edge",
        ],
        sensory: [
          "the hum of power lines",
          "gravel crunching under a single step",
          "last warmth leaving the concrete",
          "frost patterns on the car hood",
          "the white noise of a distant drone propeller",
          "helicopter passing overhead, then nothing",
          "cold railing damp from the fog",
          "sun-warmed creosote from the boardwalk",
          "cold creek air spilling out from under the bridge",
          "cold metal rail under the palm",
          "sunburn heat still rising from the neck at dusk",
        ],
        traces: [
          "a single shoe on the power line",
          "faded chalk on the sidewalk",
          "cigarette butt still warm on the ledge",
          "tire tracks through the mud",
          "rope swing over the river, fraying",
          "dog leash tied to the bike rack, no dog",
          "AirPod case cracked on the boulder",
          "garden hose left running slow",
          "mud on the gate latch",
          "old bike reflector in the ditch",
          "dog waste bag hung from the fence, forgotten",
        ],
        absences: [
          "footprints ending at the water",
          "dry fountain basin with one brown leaf",
          "park bench where the plaque was pried off",
          "picnic table chained to the post, no table now, just chain",
          "star cluster the light pollution won't let through",
          "echo off the canyon wall, barely there since the road went in",
          "still water with no wake",
          "empty nest under the eave",
          "the second boot print, washed out by seep water",
          "the picnic table shade after the cottonwood came down",
        ],
        turns: [
          "the wind changing direction",
          "a dog barking once across the valley",
          "a car door slamming in the parking lot",
          "the sprinkler timer clicking on",
          "the temperature dropping with the cloud",
          "the gate banging shut behind",
          "a plane crossing the gap in the clouds",
          "the wind dropping flat",
          "the crows scattering from the pole",
        ],
      },
      // Cluster 3: water-edge — shoreline, dock, tide pool, boat ramp,
      // reservoir overlook, creek, salt marsh, riverbank, pier, inlet
      {
        frames: [
          "fishing pier, low tide",
          "dock at the end of the lake",
          "riverbank where the current slows",
          "lighthouse walkway, wind picking up",
          "park fountain turned off for the season",
          "beach at low tide, footprints filling with water",
          "tide pool at midday",
          "wooden footbridge, no wind",
          "boat launch after the first freeze",
          "canal towpath at dawn",
          "river gauge station, green numbers on the post",
          "reservoir overlook, water line twenty feet down",
          "marsh boardwalk, morning fog",
          "beaver pond overlook, mosquito cloud in the alder shade",
          "river gravel bar at dawn, fog below the knees",
        ],
        anchors: [
          "a leaf spinning in an eddy",
          "heron standing on one leg",
          "snail crossing the wet step",
          "turtle surfacing in the pond",
          "frog half-submerged, eyes above the water",
          "fish jumping once and not again",
          "carp surfacing near the kayak launch, once",
          "kingfisher on the low branch",
          "mayfly husks clinging to the bridge rail",
          "salamander under the wet plank",
          "frog egg mass at the pond edge",
          "muskrat carrying reeds across the canal mouth",
          "otter slide polished into the muddy bank",
          "sandhill crane stepping out of the marsh grass",
          "trout holding still in the seam below the rocks",
        ],
        sensory: [
          "water trickling somewhere unseen",
          "algae smell at the water's edge",
          "salt on the lips from spray",
          "the sting of gnats at the edge of still water",
          "wet neoprene smell from the kayak rack",
          "pine pollen film on the pond skin near shore",
          "river mist on the cheeks",
          "snowmelt cold through the sock",
          "sun-warmed plywood smell from the overlook sign",
        ],
        traces: [
          "fishing line tangled in the reeds",
          "boot print on the dock plank",
          "kayak strap left looped around the dock cleat",
          "bent fishing hook in the sand",
          "orange peel spirals drying on the dock cleat",
        ],
        absences: [
          "dry creek bed, pebbles white in the sun",
          "the ford, knee-deep gravel, no crossing marker",
          "the osprey platform, nest gone",
          "the dock ladder rung below the waterline, not visible anymore",
          "dock cleat with no rope looped around it",
          "the crossing log gone from the creek, only wet cuts in the bank",
          "the wind sock at the boat launch, torn down to one strip",
          "the gravel bar where kids skipped stones, under deep water now",
          "the old rope at the swimming hole, stump and knot scars only",
        ],
        turns: [
          "the wind changing direction",
          "the bird going quiet",
          "the hawk folding its wings",
          "a fish surfacing, one ring",
          "the temperature dropping with the cloud",
          "a plane crossing the gap in the clouds",
          "the heron lifting off",
          "a flock lifting at once",
          "the wind dropping flat",
        ],
      },
    ],
};
