// ── TRANSIT (10%) ───────────────────────────────────────────────
// Movement through space. Uses SCENE CLUSTERS because road,
// rail/air, and micro-transit have different sensory worlds.

export const transit = {
    name: "transit",
    weight: 10,
    scenes: [
      // Cluster 1: Road and vehicle — cars, buses, highways, gas stations
      {
        frames: [
          "overnight bus, everyone asleep but you",
          "taxi backseat, watching the meter",
          "highway rest stop, 1am",
          "car on a back road, headlights only",
          "rental car, adjusting someone else's mirrors",
          "gas station, filling up at dawn",
          "moving truck, everything you own behind you",
          "the on-ramp, merging",
          "drive-through at midnight, only car in the lot",
          "freeway overpass, walking across",
          "EV charging station, dashboard says 40 minutes to 80%",
          "range indicator dropping, next charger 47 miles",
          "construction zone, flagperson holding the sign",
          "speed camera flash in the rearview",
          "long bridge across the grey bay, no exits",
          "closed tollbooth lane, orange cones",
          "summit pull-off, engine ticking cool",
          "traffic gantry overhead, the camera watching",
          "predawn highway, full moon in the windshield",
          "the exit you always take, muscle memory turning",
          "truck stop under buzzing canopy lights",
          "underpass in the rain",
          "school pickup lane after the last bell",
          "car wash vacuum bay, receipt on the dash",
          "car rental return lane before sunrise",
          "roadside charger behind the motel ice machine",
          "parked car at the turnout, hazard lights and fog",
          "rental EV at 6am, charger screen asking again",
          "toll plaza lane, no attendant in the booth",
          "charger bay at dawn, cable hanging loose",
          "county line weigh station bypass lane, sunrise in the mirrors",
          "flood detour lane, temporary signal blinking red",
        ],
        anchors: [
          "telephone poles passing one by one",
          "rain sliding sideways on the window at speed",
          "someone's porch light visible for three seconds",
          "windshield wipers keeping imperfect time",
          "headlights finding the deer's eyes, then not",
          "power lines dipping and rising between poles",
          "the horizon tilting as the road curves",
          "the odometer turning over",
          "fog erasing the road behind you",
          "a billboard for something already closed",
          "rest stop vending machine glowing in the dark",
          "dashcam catching the near-miss, red light runner",
          "car transporter passing, every car facing backwards",
          "delivery trucks in both mirrors, box after box",
          "the charging cable not quite reaching from the wrong side",
          "autonomous test car with the dome on top, no hands on the wheel",
          "crane shadow crossing six lanes of traffic",
          "dash light blinking low fuel",
          "steam rising from the hood",
          "bug splatter catching the sunrise on the windshield",
          "hazard lights ticking in the fog",
          "navigation voice cutting out at the state line",
          "windshield toll transponder blinking red once",
          "taillights ahead disappearing over the rise",
          "truck mirror throwing sunrise back across the lane",
          "gas price sign with one dead digit",
          "sunrise catching the bug splatter on the glass",
          "truck stop squeegee frozen to the bucket rim",
          "sun glare flashing off a cracked windshield chip",
        ],
        sensory: [
          "engine vibration through the seat",
          "cold air from the cracked window",
          "white noise of tires on wet road",
          "rumble strips buzzing under the wheels",
          "gasoline smell on the hands",
          "the particular silence when the engine turns off",
          "stale air and old upholstery",
          "bridge expansion joint thumping under the tires",
          "new asphalt smell on the repaved stretch",
          "the silence of the electric engine at the stoplight",
          "hood shimmer in the heat, the road bending",
          "dashboard fan clicking to a new speed",
          "cold steering wheel through thin gloves",
          "heavy rain drowning the wipers, pulling over",
          "road surface change vibrating through the floor",
          "mountain road, one cold breath of pine through the gap",
          "rest stop coffee, burnt, machine-made",
          "sunscreen and road trip sweat on the headrest",
          "brake dust smell at the toll plaza",
          "wind sneaking through a door seal",
          "defroster air drying one hand on the wheel",
          "windshield washer fluid sharp in the cold",
          "sun visor velcro ripping in the heat",
          "truck wash mist blowing across the pumps",
          "seatbelt edge warm where the sun finds it",
          "gas pump handle cold with dew",
          "bridge deck thumping under the wheels",
          "road salt crust on the floor mat",
          "sun visor mirror warmth on the knuckles at dawn",
          "heater fan carrying french fry salt from the paper bag",
        ],
        traces: [
          "names scratched into the seat back",
          "gum under the armrest",
          "someone's playlist still connected to the car bluetooth",
          "toll receipt on the dashboard",
          "dent in the guardrail, flowers tied to the post",
          "mile marker, same number as your age",
          "rest stop map with a you-are-here dot worn away",
          "air freshener from three owners ago",
          "travel mug from a city three states back",
          "fast food bag crumpled behind the seat, unknown age",
          "charging cable draped over the seatbelt anchor",
          "EV charging app history: seven stations, three worked",
          "windshield bug pattern from the agricultural valley",
          "sunscreen handprint on the passenger window",
          "receipt from the gas station that's now a solar farm",
          "parking ticket in the door pocket, weeks old",
          "receipt folded under the sun visor",
          "mud on the floor mat",
          "drive-through napkins in the door pocket",
          "charging station screen protector bubbled at one corner",
          "road atlas under the seat with one state highlighted",
          "charger receipt curling on the dashboard in the sun",
          "drive-through receipt stuck to the cup holder",
          "bugs caught in the grille from three states of weather",
          "old oil change sticker on the windshield",
          "sunglasses case sliding under the seat",
        ],
        absences: [
          "the town you passed through and can't remember the name",
          "the exit you missed on purpose",
          "the view behind the fog",
          "the old alignment visible through the weeds beside the on-ramp",
          "empty lot, a concrete foundation slab",
          "the stars above the highway lights",
          "the gas station from last year, now just a foundation",
          "the diner still listed in the app, dark when you arrive",
          "the EV charger on the map, out of service",
          "the rest stop bathroom, closed, no explanation",
          "the truck you were following, gone",
          "the road marking worn away",
          "the paper map in the glove box, long gone",
          "the next rest area, crossed out on the sign",
          "the shoulder lane the cones already took back",
          "the exit sign for the old route, removed",
          "the charger listed on the app, lot locked behind a chain",
          "the closed motel office window, key hooks visible through the glass",
          "the bridge light out on the far span",
          "the road after the washout",
          "the rest stop picnic tables, chained off for repairs",
          "the shoulder pullout, concrete pad with four bolt holes",
        ],
        turns: [
          "the bus pulling away before the last hand goes up",
          "the turn signal clicking on the empty dash",
          "the car ahead braking for nothing",
          "the GPS recalculating mid-sentence",
          "the toll gantry flashing, then nothing",
          "the lane closing to one, cones ahead",
          "the traffic light cycling with no one waiting",
          "the gas pump clicking off early",
          "a horn behind, then silence",
          "the windshield wiper catching and dragging",
        ],
      },
      // Cluster 2: Rail and subway — trains, platforms, underground
      {
        frames: [
          "train window, passing through small towns",
          "subway tunnel between stations",
          "departure board, all delayed",
          "platform at the end of the line",
          "the escalator down to the platform",
          "commuter train, standing room, morning",
          "sleeper car, watching fields at midnight",
          "subway platform, the countdown clock wrong",
          "train station cafe, ten minutes to boarding",
          "the transfer platform, wrong side, running",
          "rail yard at dawn",
          "night train sleeper berth",
          "light rail stop in sleet",
          "platform bench under the heat lamp",
          "station underpass, buskers gone home, echo left",
          "platform end by the signal box, cold bench",
          "station platform in lake wind, hat held on",
          "commuter rail bike car, straps knocking lightly",
          "station stairwell after the last train",
          "tunnel platform with wet footprints",
          "elevated platform over the freight yard, wind cutting through",
          "subway mezzanine, one staircase closed behind yellow tape",
        ],
        anchors: [
          "freight train passing, car after car after car",
          "tunnel lights strobing on sleeping faces",
          "the moment the city lights appear over the hill",
          "someone waving from a porch you'll never pass again",
          "the departure board flipping, everyone looks up",
          "ticket punch on the curve, conductor bracing",
          "child pressed to the window, naming everything",
          "the stopped train, no announcement, then moving again",
          "subway doors closing on a backpack strap",
          "graffiti on the tunnel wall, visible for one second",
          "signal mast changing from red to green",
          "station pigeons scattering from the rails",
          "commuter asleep against the window, stop already passed",
          "train conductor leaning out for the all-clear",
          "the yellow line trembling before the train appears",
          "someone lifting the suitcase over the gap on the second try",
          "signal light turning green on wet steel",
          "someone folding the paper ticket smaller with each delay",
          "train headlights swelling in the tunnel",
          "another train sliding past on the far side",
          "platform digital clock skipping a minute ahead",
          "train map LED flickering between two station names",
        ],
        sensory: [
          "diesel smell at the platform",
          "the lurch of the train stopping",
          "the temperature change entering a tunnel",
          "steel wheels screeching on the curve",
          "the draft of the arriving train",
          "August heat on the open platform",
          "the deceleration pressing everything forward",
          "the vibration of the window against the forehead",
          "the underground warmth rising from the subway grate",
          "brake dust and ozone on the platform",
          "station wind tugging at your coat",
          "the ring of steel under the wheels",
          "wet wool steaming inside the carriage",
          "platform grit under the heel",
          "hot brake smell under the station roof",
          "wet newspaper smell inside the winter carriage",
          "platform coffee cooling through the cardboard seam",
          "subway brake dust on the tongue",
          "warm air from the tunnel mouth",
          "window glass vibrating against the temple",
          "heater vent blowing dry air at ankle height",
          "damp wool sleeve cooling against the window frame",
        ],
        traces: [
          "a forgotten paperback in the seat pocket",
          "scratched plexiglass with someone's tag",
          "a coffee ring on the fold-down tray",
          "worn armrest where a thousand elbows rested",
          "transfer ticket punched twice, creased in the pocket",
          "someone's newspaper left folded to the crossword",
          "adapter plugged into the armrest port, owner gone",
          "coffee cup sleeve on the platform",
          "lost glove on the bench",
          "route map sticker peeled back at the corner",
          "earbud case under the bench, lid gone",
          "delay notice layered over an older delay notice",
          "ticket stub soft from a whole day in the pocket",
          "route map bubbled from years of heater vents",
          "seat reservation slip tucked in the window frame",
          "scratched window with initials",
          "umbrella drip puddle by the doorway",
        ],
        absences: [
          "the person who got off at the last stop",
          "the announcement you couldn't quite make out",
          "the platform the express train doesn't stop at",
          "the seat that was empty a moment ago",
          "the local line that doesn't run after midnight",
          "the station name you can never read at speed",
          "the train that should have already arrived",
          "the sign for the closed line",
          "the paper timetable behind the scratched plastic",
          "the escalator, stairs only tonight",
          "the cafe cart already rolled away from the platform",
          "the arrival board line for your train, suddenly blank",
          "the bench under the heat lamp, one screw left",
          "the train door by car six, taped off again",
          "the platform staff room dark behind glass",
          "the station cafe with shutters down",
          "the last local train line on the map, stickered over",
          "the staffed ticket window, blinds down since spring",
        ],
        turns: [
          "the train horn sounding twice",
          "the overhead compartment popping open mid-turn",
        ],
      },
      // Cluster 3: Airports and flights — terminals, gates, cabins, customs
      {
        frames: [
          "airport terminal, between flights",
          "TSA line, shoes in the bin",
          "gate area at 5am, half the seats sleepers",
          "boarding group C, watching A file past",
          "terminal tram, the same loop again",
          "customs hall, fluorescent and silent",
          "jet bridge in the rain",
          "baggage claim at 2am",
          "gate change across the terminal, backpack half-zipped",
          "rental car shuttle curb, midnight breeze",
          "rental car shuttle line, fluorescent vests in the drizzle",
          "gate area after the red-eye boards, charging cords still plugged in",
          "gate area after midnight, carpet full of charger bricks",
          "arrivals curb in the rain, neon reflecting off luggage",
          "security lane at 5am, bins stacked high",
          "baggage carousel under the flight board",
          "airport tram platform, doors opening to no one boarding",
          "gate carpet corner taped down near the charging pillar",
        ],
        anchors: [
          "the shadow of the plane crossing a parking lot",
          "the seatback flight map showing the plane over ocean",
          "the intercom cutting out mid-word",
          "luggage appearing on the carousel, third time around",
          "the customs stamp, one page left in the passport",
          "the plane banking, the whole city tilting in the window",
          "carousel numbers spinning past",
          "gate agent folding the final paper",
          "someone repacking the carry-on on the carpet by the wall",
          "the tray of belts and watches circling back alone",
          "seatbelt sign flicking on over sleeping strangers",
          "customs officer stamping the last blank corner",
          "boarding pass refusing the scanner on the first try",
          "baggage carousel starting up with nobody at it yet",
          "a cart of abandoned shoes by security",
          "carousel flap lifting for the next bag",
          "gate monitor switching to final call with half the seats still full",
          "crew member counting standby slips under the podium lamp",
        ],
        sensory: [
          "jet bridge cold between the terminal and the plane",
          "turbulence rattle of the tray table",
          "the descent pressure in the ears",
          "cold seatbelt buckle against the wrist",
          "the particular staleness of airport carpet",
          "recycled cabin air, dry in the throat",
          "carpet muffling every footstep in the terminal",
          "jet fuel smell on the jet bridge",
          "the double beep of the scanner",
          "pretzel salt on dry airplane fingers",
          "cold air spilling from the jet bridge seal",
          "lotion and recycled air at thirty thousand feet",
          "escalator handrail cold from the terminal AC",
          "dry cabin air still in the throat after landing",
          "cold jet bridge metal through the carry-on handle",
          "carpet swallowing footsteps",
          "suitcase wheels clacking on tile",
          "airplane blanket static catching on the sleeve",
          "jet bridge rubber seal smell lingering on the coat",
        ],
        traces: [
          "boarding pass used as a bookmark",
          "sticker on the suitcase from the last trip",
          "airsick bag with a child's drawing on it",
          "duty-free receipt in the jacket pocket, wrong currency",
          "neck pillow deflated in the carry-on",
          "luggage tag with an address two moves ago",
          "decade of passport stamps, the ink fading",
          "compensation form filled out, never submitted",
          "boarding pass tucked in the passport",
          "gate check tag torn at the staple",
          "gate sticker half-peeled from the water bottle",
          "baggage carousel rubber marked with black suitcase wheels",
          "gate-change sticker slapped over the old gate number",
          "toothbrush in the quart bag still damp",
          "gate-check tag stapled to the boarding pass",
          "toothpaste squeezed flat in the quart bag",
          "security bin sticker on the jacket sleeve",
          "phone charger left at the outlet",
        ],
        absences: [
          "the arrivals hall, one sign held up, nobody walking toward it",
          "the view from the window seat, cloud cover all the way",
          "the connection that doesn't exist anymore",
          "the checked bag that never reached the carousel",
          "the seat next to you, still empty",
          "the water bottle emptied at security, pocket still wet",
          "the gate seat nearest the outlet, taken before dawn",
          "the overhead bin space above your row",
          "the baggage carousel screen after the flight number drops off",
          "the pen for the customs form, string cut long ago",
          "the seat near the outlet, jacket there, owner nowhere",
          "the bag that never came off the carousel",
          "the gate outlet with a free socket",
          "the checked stroller at oversize pickup, tag still clipped to the counter",
          "the water fountain past security, wrapped for maintenance",
        ],
        turns: [
          "the overhead compartment popping open mid-turn",
          "the elevator doors opening a floor early",
          "the gate agent calling a standby name",
          "the seatbelt sign chiming off over sleeping rows",
        ],
      },
      // Cluster 4: Ferries and water — docks, crossings, bridges on foot
      {
        frames: [
          "ferry crossing at dusk",
          "ferry gangway, last call",
          "bridge on foot, halfway across, water below",
          "dock at night, the last boat already gone",
          "river taxi, the city passing on both sides",
          "canal lock, water rising slowly",
          "ferry terminal at first light",
          "pedestrian bridge over black water",
          "water taxi dock in the drizzle",
          "ferry stairwell, everyone crowding before docking",
          "ferry terminal snack counter, shutters half down",
          "vehicle deck after engines cut, everyone waiting to move",
          "ferry terminal bench, gull feathers in the corner",
          "harbor footbridge in fog, shoes ringing on metal grating",
          "harbor terminal in cold rain",
          "lock gate with water climbing",
          "ferry slip in freezing rain, deck lights reflecting on black water",
          "harbor queue lane, bike helmets dripping on the rail",
        ],
        anchors: [
          "the ferry wake spreading behind, seagulls following",
          "salt spray on the ferry deck hitting the phone screen",
          "the far shore getting closer but not fast enough",
          "a cormorant diving off the piling as the ferry passes",
          "the bridge cables humming in the wind",
          "ropes tightening against the cleats",
          "wake folding into the pilings",
          "orange life ring swinging once against the rail",
          "plastic poncho snapping on the upper deck",
          "deckhand coiling the wet line in one-arm loops",
          "orange sodium light breaking on the harbor chop",
          "deck light shaking on the black wake",
          "the ferry horn rolling across the dark water twice",
          "deckhand coiling wet rope",
          "rope fender bumping the hull",
          "deckhand flashlight beam on the wet ramp bolts",
          "orange deck cone sliding with each wake slap",
        ],
        sensory: [
          "salt spray on the ferry deck",
          "the ferry hull clanking against the dock",
          "diesel exhaust mixing with salt air",
          "cold railing wet from spray",
          "the engine vibration through the deck plates",
          "wet rope fiber in the palm",
          "fog damp on the jacket",
          "salt drying on the lips after the crossing",
          "harbor diesel hanging low under the awning",
          "rubber boot squeak on the painted deck",
          "metal bench wet clear through the coat",
          "salt wind through the jacket zipper",
          "wet aluminum bench under the thighs",
          "engine thrum through the deck",
          "boot soles squeaking on painted steel",
          "harbor wind pushing diesel into the ferry stairwell",
          "wet glove cuff collecting salt at the wrist",
        ],
        traces: [
          "gum on the ferry railing, layers of it",
          "life jacket instructions nobody reads",
          "tide chart pinned inside the wheelhouse window",
          "paint peeling on the bollard, rope-worn",
          "rope burns on the dock post",
          "muddy footprints on the gangway",
          "dock cleat polished bright where the line bites",
          "schedule taped inside the fogged terminal window",
          "paper ticket soft at the fold from mist",
          "life ring bracket rusting in a salt outline",
          "coffee lid rolling in the ferry stairwell",
          "dock ticket stub stuck to the sole",
          "salt line on the piling at high water",
        ],
        absences: [
          "the ferry route discontinued last season",
          "the far shore, lost in fog",
          "the boat that just left, wake still rocking the dock",
          "the dockhand gone from the pier",
          "the last boat's wake gone flat",
          "the next crossing canceled on the hand-lettered board",
          "the gulls gone quiet before the squall",
          "the shoreline lights on the far island, fog took them",
          "the upper deck benches, chained for the storm",
          "the island timetable line painted over on the board",
          "the gangway rail where the rope fender used to hang",
          "the next boat already gone",
          "the old ticket office window",
          "the ferry bike rack row with one lock still clipped",
          "the last evening crossing posted, then taped over",
        ],
        turns: [
          "a horn behind, then silence",
        ],
      },
      // Cluster 5: Micro-transit and new mobility — rideshares, e-scooters,
      // bike shares, EVs, delivery robots, last-mile movement
      {
        frames: [
          "rideshare backseat, GPS and driver disagreeing",
          "e-scooter graveyard at the edge of the park",
          "bike share dock, one bike left, tire soft",
          "autonomous shuttle looping the campus, empty",
          "delivery robot on the curb, waiting to cross",
          "EV charging plaza, four cars, three staring at phones",
          "curbside pickup lane, hazard lights in a row",
          "pickup pin a block over, four lanes of traffic between",
          "rideshare pickup under an awning",
          "shared bike rack at the station",
          "bike lane under the freeway, app still searching",
          "curbside charger at the grocery store, one orange cone",
          "scooter unlock screen in the freezing drizzle",
          "rideshare pickup curb outside the stadium, battery saver on",
          "shared scooter corral after the concert let out",
          "bike-share map kiosk, touchscreen damp with fog",
          "rideshare curb in the rain",
          "loading zone with hazard lights on",
          "bike lane detour around a food delivery queue",
          "micro-mobility parking pad painted over old taxi markings",
        ],
        anchors: [
          "e-scooter tipping over on the sidewalk, nobody near it",
          "rideshare driver circling the lot, searching for the pin",
          "phone at 1%, the charging icon not appearing fast enough",
          "delivery drone recalculating above the intersection",
          "autonomous shuttle stopping for a plastic bag in the road",
          "bike share app scanning the dock, no available bikes",
          "delivery van double-parked, hazards on, driver running",
          "helmet clipped to the handlebar",
          "tail light blinking on the scooter",
          "scooter headlight blinking in a pile of fallen leaves",
          "rideshare plate checked twice in the rain",
          "shared bike basket holding someone else's wilted flowers",
          "delivery robot stuck at the tactile paving, polite chime repeating",
          "delivery bot waiting patiently for a leaf to stop moving",
          "rideshare trunk opening to three identical black suitcases",
          "hand reaching for the wrong car door",
          "charger cable stretched under the cone",
          "delivery app map rerouting as the rider misses the turn",
          "shared bike app timer dipping under one minute at the dock",
        ],
        sensory: [
          "e-scooter whine going uphill",
          "pine-chemical air freshener in the rideshare",
          "bike dock click and clunk when the bike locks in",
          "surge pricing notification buzz in the pocket",
          "cold handlebar through thin gloves, morning",
          "the quiet of the autonomous shuttle door closing",
          "pothole shock through the scooter deck, up the spine",
          "rubber tires over brick",
          "headwind on the open lane",
          "charger fan noise under the canopy lights",
          "phone case slick with drizzle at pickup",
          "phone vibration through the glove fingertip",
          "charger cable stiff from the cold",
          "scooter brake squeal in the damp",
          "battery pack heat through the coat pocket",
          "cold grip tape under thin gloves",
          "puddle splash against the ankle",
          "phone speaker navigation clipping in and out under the overpass",
          "helmet strap chafe under a damp collar",
        ],
        traces: [
          "QR code on the scooter, half scraped off",
          "4.8 rating in the rideshare app, one unexplained star missing",
          "delivery robot tire tracks through the flower bed",
          "bike helmet hanging from the dock, no bike",
          "damp charging cable on the sidewalk post",
          "rate-your-ride prompt still on the screen, door already closed",
          "charging plug left hanging from the dock",
          "rubber mark at the curb cut",
          "promo code flyer tucked into the bike basket",
          "helmet hair net stuffed in the scooter cup",
          "helmet disinfecting wipes in an empty dock tray",
          "old promo sticker on the scooter stem, sun-faded",
          "promo ride credit expired on the lock screen",
          "charging port flap dangling from the scooter stem",
          "worn grip tape by the throttle",
          "mud stripe under the fender",
        ],
        absences: [
          "the parking spaces converted to a bike lane, cars circling",
          "the bike dock empty since 7am, full by midnight",
          "the pedestrian already gone when the scooter arrives",
          "the driver who canceled at the curb",
          "the bus stop sign removed after the line changed",
          "the charging cable your app said was available",
          "the pickup pin drifting another half block",
          "the one open charger hidden behind the idling SUV",
          "the bike lane paint already worn from the snowplow",
          "the curb ramp, blocked by the parked van again",
          "the bike your app reserved, dock light already green for someone else",
          "the open dock with no bikes left",
          "the sidewalk clear of parked scooters",
          "the designated pickup bay with no painted number left",
          "the bike-share kiosk, map bracket empty, sun on the screen",
        ],
        turns: [
          "the bus pulling away before the last hand goes up",
          "the GPS recalculating mid-sentence",
          "the scooter's front wheel hitting a pothole",
          "the windshield wiper catching and dragging",
          "the lane closing to one, cones ahead",
        ],
      },
    ],
};
