// ── URBAN-NATURE (20%) ──────────────────────────────────────────
// Nature persisting in built environments. All entries share
// urban/industrial settings where something wild is happening.

export const urbanNature = {
    name: "urban-nature",
    weight: 20,
    scenes: [
      // Cluster 1: street-level — sidewalks, crosswalks, storm drains, chain-link fences, curbs, tree pits, crosswalk buttons, sidewalk cracks, mailboxes, lamp posts
      {
        frames: [
          "sidewalk crack at the crosswalk",
          "bus shelter in the rain",
          "traffic island between lanes",
          "median strip, wildflowers somehow",
          "storm drain at the curb",
          "corner lot with a bent chain-link gate",
          "stormwater planter outside the courthouse",
          "delivery robot waiting at the crosswalk",
          "bike lane buffer strip, weeds between the bollards",
          "supermarket lot edge, volunteer sunflowers by the cart return",
          "rain garden beside the parking lot",
          "retaining wall with fern seams",
          "under the elevated train, volunteer plum tree in the fence corner",
          "school parking lot bioswale, rainwater still standing at sunset",
          "gas station at the edge of town",
          "co-working space window, ground floor",
          "pop-up market alley, Monday morning",
          "warehouse district, weekend morning",
        ],
        anchors: [
          "dandelion splitting the asphalt",
          "tree roots lifting the sidewalk",
          "weed blooming in the chain-link diamond",
          "raccoon prints on the car hood",
          "earthworm on the sidewalk after rain",
          "caterpillar crossing the painted crosswalk arrow",
          "spider web strung between two parking meters",
          "praying mantis on the parking ticket machine",
          "snail crossing the painted bike symbol",
          "opossum nosing along the chain-link base",
          "roots lifting the curb",
          "salamander in the storm drain",
          "bees in the rosemary planter",
          "sapling bending in a curb cut",
          "bee slipping into the window box basil",
          "mourning dove nesting in the traffic signal hood",
          "honeybee swarm settled on the traffic signal mast",
          "mallards nesting in the planter outside the bank",
          "seeds sprouting in the base of the bike-share dock",
          "sparrow carrying french fry crumbs into the awning vent",
        ],
        sensory: [
          "petrichor mixing with exhaust",
          "warm gust from the subway grate",
          "rain drumming on the awning",
          "the vibration of a passing truck",
          "wet brick underfoot",
          "the hiss of bus brakes",
          "the click of the walk signal changing",
          "diesel and honeysuckle at the intersection",
          "clover smell rising from the cracked concrete median",
          "moss damp underfoot where the downspout drains",
          "car exhaust and wild fennel at the same moment",
          "wet cardboard and city mud after the overnight rain",
          "rainwater smell lifting from the hot concrete joints",
          "mulch steam rising from the curb cut planter",
          "hot brake smell from the delivery van and mint from the tree pit",
          "sprinkler overspray misting the bike lane in full sun",
          "storm drain cool air on the ankles",
          "freezer truck condenser heat blasting across the crosswalk",
          "night irrigation hiss from the median flower beds",
        ],
        traces: [
          "bread crumbs in a careful line on the wall",
          "bird house zip-tied to the stop sign",
          "seed bombs in the vacant lot",
          "hand-painted sign: please don't mow the wildflowers",
          "pollinator strip along the parking lot edge, city permit on the post",
          "wildflower seed packets rubber-banded to the bus shelter post",
          "hand-lettered sign on the chain link: fox den — keep dogs out",
          "guerrilla-planted milkweed in the highway median",
          "chalk arrows on the sidewalk pointing to the community garden",
          "QR code sticker on the lamp post: track the peregrine nest",
          "native plant ID tags zip-tied to the vacant lot fence",
          "cardboard tray of marigold starts by the curb cut",
          "twine holding up the volunteer sunflower",
          "laminated notice on the planter: monarch waystation",
          "popsicle-stick plant labels in the median mulch",
          "cut milk jug over the sapling stake as a wind guard",
          "seed packet tucked behind the bus schedule case",
          "drip hose along the curb strip",
          "zip-tied spoon as a birdbath in the median planter",
          "hand-lettered sign on cardboard: leave the bee weeds",
          "painted rock border around the curbside herb patch",
        ],
        absences: [
          "bench in full sun, stump beside it",
          "birdsong you can't quite hear over the AC units",
          "the creek under the parking lot",
          "where the elm was before the storm",
          "the milkweed patch mowed before the monarchs came back",
          "the weedy margin the city finally cleared",
          "the puddle the sparrows used, storm drain unplugged last week",
          "the wildflower strip under the new sidewalk",
          "the gap in the fence the fox used every night",
          "the feral cat colony, notices still posted but no cats",
          "the tree pit with no tree",
          "the fox path through the vacant lot, paved over",
          "empty tree pit after the cut",
          "the curbside pollinator sign post with no sign left on it",
          "the volunteer watering jug at the tree pit, gone by noon",
        ],
        turns: [
          "the bus pulling away from the stop",
          "a jackhammer starting up the block",
          "the streetlight blinking on early",
          "someone kicking a can down the sidewalk",
          "a taxi honking, pigeons scattering",
          "the bodega cat stepping into the sun",
          "the grate steam shifting direction",
          "a window slamming shut above",
          "the crosswalk signal clicking to walk",
          "the delivery truck backing up, beeping",
          "a skateboard sound coming closer",
          "the construction crane swinging overhead",
          "rain starting on the hot pavement",
          "the pigeon flock lifting at once",
          "bus doors folding open",
          "manhole cover rattling under a truck",
          "street sweeper brushing the curb",
        ],
      },
      // Cluster 2: aerial-or-structural — rooftops, bridge decks, tower platforms, power lines, solar-panel roofs, fire escapes, water towers, antennas, billboards, overpasses
      {
        frames: [
          "fire escape above the bodega",
          "rooftop garden, downtown",
          "office window, fourteenth floor",
          "hotel balcony facing the freeway",
          "green roof on the corporate headquarters",
          "5G tower on the old water tank",
          "rooftop HVAC array, mid-summer",
          "rooftop water tank, winter light",
          "parking garage roof, volunteer sumac at the seam",
          "solar farm access road at dawn",
          "EV charging station in the mall parking lot",
          "data center cooling yard, exhaust fans running",
          "tech campus courtyard, no one out yet",
          "stairwell window, parking structure",
          "apartment courtyard at dusk",
          "hospital courtyard",
          "subway platform, rush hour",
          "construction site after hours",
        ],
        anchors: [
          "pigeon nesting in the exit sign",
          "hawk perched on the traffic light",
          "vine climbing the fire escape",
          "peregrine falcon diving between buildings",
          "bees working the rooftop lavender",
          "owl in the stadium lights",
          "starlings nesting in the EV charger housing",
          "kestrel perched on the 5G antenna",
          "wasp colony in the cracked solar panel frame",
          "bat roosting behind the HVAC access panel",
          "lichen spreading across the rooftop solar array",
          "hawk carrying a pigeon past the glass office tower",
          "crow dropping a clam on the parking structure roof",
          "tomato vine spilling from a fifth-floor fire escape bucket",
          "swallow nesting under the bridge lip",
          "ivy pulling the mortar from the bricks",
          "moths crowding the data center exhaust vent at night",
        ],
        sensory: [
          "steam rising from the manhole",
          "neon reflected in a puddle",
          "streetlight buzzing on its last legs",
          "metal railing warm from the sun",
          "warm dry exhaust from the data center fans",
          "ozone smell after the electric bus pulls away",
          "cool updraft from the green roof drain",
          "the low hum of the EV chargers, unceasing",
          "grackle call cutting through the parking garage echo",
          "insect hum louder than the AC unit, briefly",
          "hawk cry bouncing between glass towers",
          "hot tar and bee hum, rooftop noon",
          "AC condensate dripping into the alley moss",
          "substation buzz under the sparrow chatter",
          "rainwater metallic taste under the railroad bridge",
        ],
        traces: [
          "rain gauge wired to the balcony rail",
          "nesting box bolted to the utility pole, facing east",
          "shallow dish of water wedged under the EV charger base",
          "bucket of sand left by the loading dock, birds bathing in it",
          "strip of burlap tied around the young street tree, someone worried about frost",
          "upturned bottle drip-watering the tree pit planting",
          "coffee can nailed to the fence post, full of birdseed",
          "birdseed scattered on the stair landing",
          "milk crate shade frame over a new street tree",
          "rain-chain made from old keys beside the alley planter",
          "rain barrel under the downspout",
        ],
        absences: [
          "stars hidden behind the light pollution",
          "the hawk nest on the ledge, scaffolding over it now",
          "the bat box on the building they demolished",
          "tree canopy the new building's shadow replaced",
          "the ivy stripped off the wall for waterproofing",
          "the rooftop hive boxes after the landlord changed hands",
          "the swallow nest under the awning, mud ring only",
          "the swallow gap above the roll-up door, sealed with foam",
          "the vine trellis removed, anchor hooks still in the brick",
          "the swallow nest shelf bracket with no mud cup this year",
          "the ivy corner at the retaining wall scraped to bare concrete",
        ],
        turns: [
          "the streetlight blinking on early",
          "the fire escape dripping onto the ivy",
          "a window slamming shut above",
          "the construction crane swinging overhead",
          "the pigeon flock lifting at once",
        ],
      },
      // Cluster 3: underpass-or-lot — bike underpasses, loading docks, parking decks, alleys, sound barriers, railyard edges, service corridors, dumpster corners, concrete channels
      {
        frames: [
          "alley behind the restaurant",
          "parking garage, top level",
          "loading dock at dawn",
          "vacant lot between buildings",
          "underpass where the pigeons roost",
          "drainage ditch behind the strip mall",
          "decommissioned rail yard, weeds waist-high",
          "retention pond behind the warehouse",
          "bus depot fence line at first light",
          "bike underpass where the weeds stay green",
          "parking lot tree island after closing",
          "stormwater basin behind the warehouse, cattails taking hold",
          "culvert mouth under the access road",
          "clinic loading ramp, rainwater channeling through sedge clumps",
          "under the elevated train, volunteer plum tree in the fence corner",
        ],
        anchors: [
          "rat disappearing into the grate",
          "moss growing on the north side of the dumpster",
          "sparrows bathing in the AC drip",
          "coyote crossing the empty parking lot",
          "mushrooms on the rotting pallet",
          "geese on the office park retention pond",
          "fern uncurling from the storm drain",
          "fox trotting down the center line at 4am",
          "delivery robot stopped, squirrel sitting on top of it",
          "house sparrows nesting in the drive-through menu board",
          "wild mustard filling the decommissioned rail yard",
          "toad tucked against the warm brick by the dumpster",
          "gull worrying at a bag of fries under the bench",
          "crows nesting in the letters of the parking garage sign",
          "mink slipping through the drainage channel behind the warehouse",
        ],
        sensory: [
          "tar smell on a hot day",
          "coffee grounds smell from the dumpster",
          "pigeon wingbeats echoing in the underpass",
          "cold draft from the basement vent",
          "algae smell from the retention pond when the wind shifts",
          "clang of the dumpster lid, then wings",
          "traffic hiss under the overpass",
          "leaf mold smell from the storm drain",
          "drip from the fire escape landing",
          "fried oil and wet soil at the alley mouth",
          "warm rainwater dripping from the parking deck seams",
          "cool air from the culvert mouth",
          "river mud under the bridge",
          "cold air pooling at the underpass entrance",
          "steam from a manhole grate",
        ],
        traces: [
          "small water dish behind the loading dock",
          "someone planted tomatoes in a milk crate",
          "sunflower growing from the gutter",
          "community garden behind the chain link",
          "bee hotel made from a coffee can",
          "cat food can under the dumpster",
          "water left out for strays",
          "paper bag marked bat guano — good for tomatoes by the dumpster",
          "plastic takeout lid weighted with pebbles as a bird bath",
          "milk crate turned into a planter box",
          "soil spilled along the loading dock edge",
          "hand trowel left in the planter",
        ],
        absences: [
          "where the community garden was, now gravel",
          "the field this strip mall replaced",
          "empty birdhouse on the condemned building",
          "the retention pond filled in for the building expansion",
          "the alley cat that never comes back",
          "bench in open sun, no canopy overhead",
          "the shade cloth over the saplings, gone by August",
          "the patch of sun on the stoop before the tower went up",
          "the puddle in the alley the starlings used every morning",
          "rain garden dry after the trench work",
          "nest cup under the bare awning",
          "the sound of crickets from the lot that's now a parking structure",
        ],
        turns: [
          "a jackhammer starting up the block",
          "someone kicking a can down the sidewalk",
          "the grate steam shifting direction",
          "the delivery truck backing up, beeping",
          "a skateboard sound coming closer",
          "rain starting on the hot pavement",
        ],
      },
    ],
};
